// Composerdle mode II — real public-domain recordings + real score scans (Wikimedia Commons).
// pages: hotlinkable page images, first entry = first page of the movement.
// crop: fraction of first page height hidden to redact the title/composer block (verified per scan).

const UP = 'https://upload.wikimedia.org/wikipedia/commons';
const range = (a, b) => Array.from({ length: b - a + 1 }, (_, i) => a + i);
// Commons renders PDF pages as JPGs; only bucketed widths are served (960/1280 verified per file).
const pdfPages = (hash, file, width, nums) =>
  nums.map(n => `${UP}/thumb/${hash}/${file}/page${n}-${width}px-${file}.jpg`);
// self-hosted full-score pages (PD scans rendered into /scores/<slug>/)
const local = (slug, n) => range(1, n).map(i => `scores/${slug}/pg${i}.jpg`);
// BnF page-image sets hotlink via Special:FilePath (302 → upload.wikimedia, verified 200)
const bnf = (tpl, nums) => nums.map(n => tpl.replace('{N}', n));

const EASY = [
  {
    composer: 'Johann Sebastian Bach',
    title: 'Toccata and Fugue in D minor, BWV 565',
    audio: `${UP}/transcoded/b/be/Toccata_et_Fugue_BWV565.ogg/Toccata_et_Fugue_BWV565.ogg.mp3`,
    performer: 'Ashtar Moïra, Tamburini organ',
    license: 'public domain',
    scoreNote: 'Johannes Ringk manuscript — the earliest surviving source',
    crop: 0.05,
    pages: [
      `${UP}/thumb/7/71/Toccata_and_Fugue_in_D_minor%2C_BWV_565_%28Johannes_Ringk_manuscript%29.jpg/960px-Toccata_and_Fugue_in_D_minor%2C_BWV_565_%28Johannes_Ringk_manuscript%29.jpg`,
      `${UP}/thumb/b/b5/Toccata_and_Fugue_in_D_minor%2C_BWV_565_%28Johannes_Ringk_manuscript%2C_pg2%29.jpg/960px-Toccata_and_Fugue_in_D_minor%2C_BWV_565_%28Johannes_Ringk_manuscript%2C_pg2%29.jpg`,
      `${UP}/thumb/1/1b/Toccata_and_Fugue_in_D_minor%2C_BWV_565_%28Johannes_Ringk_manuscript%2C_pg3%29.jpg/960px-Toccata_and_Fugue_in_D_minor%2C_BWV_565_%28Johannes_Ringk_manuscript%2C_pg3%29.jpg`,
      `${UP}/thumb/a/a3/Toccata_and_Fugue_in_D_minor%2C_BWV_565_%28Johannes_Ringk_manuscript%2C_pg4%29.jpg/960px-Toccata_and_Fugue_in_D_minor%2C_BWV_565_%28Johannes_Ringk_manuscript%2C_pg4%29.jpg`,
      `${UP}/thumb/9/9e/Toccata_and_Fugue_in_D_minor%2C_BWV_565_%28Johannes_Ringk_manuscript%2C_pg5%29.jpg/960px-Toccata_and_Fugue_in_D_minor%2C_BWV_565_%28Johannes_Ringk_manuscript%2C_pg5%29.jpg`,
      `${UP}/thumb/5/5a/Toccata_and_Fugue_in_D_minor%2C_BWV_565_%28Johannes_Ringk_manuscript%2C_pg6of6%29.jpg/960px-Toccata_and_Fugue_in_D_minor%2C_BWV_565_%28Johannes_Ringk_manuscript%2C_pg6of6%29.jpg`,
    ],
  },
  {
    composer: 'Ludwig van Beethoven',
    title: 'Symphony No. 5 in C minor, Op. 67 — I. Allegro con brio',
    audio: `${UP}/transcoded/e/e6/Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor%2C_op._67_-_i._allegro_con_brio.ogg/Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor%2C_op._67_-_i._allegro_con_brio.ogg.mp3`,
    performer: 'Skidmore College Orchestra',
    license: 'public domain · Musopen',
    scoreNote: 'Eulenburg miniature full score',
    crop: 0.17,
    pages: local('beethoven5', 10),
  },
  {
    composer: 'Wolfgang Amadeus Mozart',
    title: 'Eine kleine Nachtmusik, K. 525 — I. Allegro',
    audio: `${UP}/transcoded/2/24/Mozart_-_Eine_kleine_Nachtmusik_-_1._Allegro.ogg/Mozart_-_Eine_kleine_Nachtmusik_-_1._Allegro.ogg.mp3`,
    performer: 'Advent Chamber Orchestra',
    license: 'CC BY-SA 2.0',
    scoreNote: 'Eulenburg study score (original string-ensemble scoring)',
    crop: 0.2,
    pages: local('mozart-ekn', 8),
  },
  {
    composer: 'Antonio Vivaldi',
    title: 'The Four Seasons — “Spring”, RV 269, I. Allegro',
    audio: `${UP}/transcoded/f/ff/Vivaldi_-_Four_Seasons_1_Spring_mvt_1_Allegro_-_John_Harrison_violin.oga/Vivaldi_-_Four_Seasons_1_Spring_mvt_1_Allegro_-_John_Harrison_violin.oga.mp3`,
    performer: 'John Harrison (violin), Wichita State University Chamber Players',
    license: 'CC BY-SA 3.0',
    scoreNote: '1775 Paris print of Rousseau’s flute arrangement',
    crop: 0,
    pages: pdfPages('3/38', 'Violin_Concerto_in_E_major%2C_RV_269_%28IA_imslp-concerto-in-e-major-rv-269-vivaldi-antonio%29.pdf', 1280, range(2, 4)),
  },
  {
    composer: 'Joseph Haydn',
    title: 'Symphony No. 94 “Surprise” — II. Andante',
    audio: `${UP}/transcoded/4/42/Haydn%3B_Symphony_No._94_%22Surprise%22%2C_2._Andante.ogg/Haydn%3B_Symphony_No._94_%22Surprise%22%2C_2._Andante.ogg.mp3`,
    performer: 'Boston Symphony Orchestra, cond. Serge Koussevitzky',
    license: 'public domain',
    scoreNote: 'Edition Cranz orchestral score',
    crop: 0,
    pages: local('haydn94', 10),
  },
  {
    composer: 'Edvard Grieg',
    title: 'In the Hall of the Mountain King (Peer Gynt Suite No. 1)',
    audio: `${UP}/transcoded/b/bb/Musopen_-_In_the_Hall_Of_The_Mountain_King.ogg/Musopen_-_In_the_Hall_Of_The_Mountain_King.ogg.mp3`,
    performer: 'Musopen Symphony Orchestra',
    license: 'public domain · Musopen',
    scoreNote: 'C. F. Peters orchestral full score',
    crop: 0.13,
    pages: local('mountainking', 10),
  },
  {
    composer: 'Pyotr Ilyich Tchaikovsky',
    title: 'Swan Lake, Op. 20 — Scène (the swan theme)',
    audio: `${UP}/transcoded/1/1f/Tchaikovsky_Swan_Lake_Op.20_No.10._Sc%C3%A8ne.ogg/Tchaikovsky_Swan_Lake_Op.20_No.10._Sc%C3%A8ne.ogg.mp3`,
    performer: 'London Philharmonic Orchestra, cond. John Barbirolli (1933)',
    license: 'public domain',
    scoreNote: 'Jurgenson orchestral full score',
    crop: 0.19,
    pages: pdfPages('2/21', 'IMSLP247444-PMLP59697-Tchaikovsky-Op20a.FSj.pdf', 960, range(2, 11)),
  },
  {
    composer: 'Frédéric Chopin',
    title: 'Piano Sonata No. 2, Op. 35 — III. Marche funèbre',
    audio: `${UP}/transcoded/b/b2/Frederic_Chopin_Piano_Sonata_No.2_in_B_flat_minor_Op35_-_III_Marche_Funebre.ogg/Frederic_Chopin_Piano_Sonata_No.2_in_B_flat_minor_Op35_-_III_Marche_Funebre.ogg.mp3`,
    performer: 'Andreas Xenopoulos (piano)',
    license: 'CC0 · Musopen',
    scoreNote: 'Breitkopf & Härtel 1878 edition',
    crop: 0,
    pages: pdfPages('a/a8', 'Piano_Sonata_No.2%2C_Op.35_%28IA_imslp-sonata-no2-op35-chopin-frdric%29.pdf', 1280, range(11, 13)),
  },
  {
    composer: 'Richard Wagner',
    title: 'Ride of the Valkyries (Die Walküre, Act III)',
    audio: `${UP}/transcoded/2/29/Richard_Wagner_-_Ride_of_the_Valkyries.ogg/Richard_Wagner_-_Ride_of_the_Valkyries.ogg.mp3`,
    performer: 'American Symphony Orchestra (Edison recording, 1921)',
    license: 'public domain',
    scoreNote: 'Schott orchestral full score',
    crop: 0.12,
    pages: local('ride', 10),
  },
  {
    composer: 'Erik Satie',
    title: 'Gymnopédie No. 1',
    audio: `${UP}/transcoded/9/90/Erik_Satie_-_gymnopedies_-_la_1_ere._lent_et_douloureux.ogg/Erik_Satie_-_gymnopedies_-_la_1_ere._lent_et_douloureux.ogg.mp3`,
    performer: 'Robin Alciatore (piano)',
    license: 'public domain · Musopen',
    scoreNote: '1888 first edition',
    crop: 0.26,
    pages: pdfPages('8/88', 'IMSLP03213-Satie-GymnopediesOrEd.pdf', 1280, range(1, 3)),
  },
  {
    composer: 'Wolfgang Amadeus Mozart',
    title: 'Rondo alla turca (Piano Sonata K. 331)',
    audio: 'https://archive.org/download/jamendo-140751/32-1169736-OnClassical-Mozart%2C%20W.A._%20Sonata%20No.%2011%20in%20A%20Major%2C%20K.%20331%20-%20III.%20Rondo%20alla%20turca%20_Turkish%20March_.mp3',
    performer: 'Alessandro Deljavan (piano, OnClassical)',
    license: 'CC BY-NC-SA 3.0',
    scoreNote: 'Eugen d’Albert edition, Forberg 1903 (BnF scan)',
    crop: 0.22,
    pages: bnf("https://commons.wikimedia.org/wiki/Special:FilePath/Rondo%20alla%20turca%20-%20aus%20der%20Sonate%20in%20A%20dur%20-%20f%C3%BCr%20Klavier%20-%20von%20W.%20A.%20Mozart%20-%20btv1b9069366j%20({N}%20of%2012).jpg?width=1280", ['05', '06', '07', '08', '09']),
  },
  {
    composer: 'Ludwig van Beethoven',
    title: 'Piano Sonata No. 14 “Moonlight” — I. Adagio sostenuto',
    audio: `${UP}/transcoded/4/48/Ludwig_van_Beethoven_-_sonata_no._14_in_c_sharp_minor_%27moonlight%27%2C_op._27_no._2_-_i._adagio_sostenuto.ogg/Ludwig_van_Beethoven_-_sonata_no._14_in_c_sharp_minor_%27moonlight%27%2C_op._27_no._2_-_i._adagio_sostenuto.ogg.mp3`,
    performer: 'Paul Pitman (piano)',
    license: 'public domain · Musopen',
    scoreNote: 'Cappi first edition, Vienna 1802',
    crop: 0,
    pages: local('moonlight', 3),
  },
  {
    composer: 'Antonín Dvořák',
    title: 'Symphony No. 9 “From the New World” — II. Largo',
    audio: `${UP}/transcoded/c/c3/Antonin_Dvorak_-_symphony_no._9_in_e_minor_%27from_the_new_world%27%2C_op._95_-_ii._largo.ogg/Antonin_Dvorak_-_symphony_no._9_in_e_minor_%27from_the_new_world%27%2C_op._95_-_ii._largo.ogg.mp3`,
    performer: 'Musopen Symphony Orchestra',
    license: 'public domain · Musopen',
    scoreNote: 'Eulenburg 1903 orchestral study score',
    crop: 0,
    pages: local('newworld', 10),
  },
  {
    composer: 'George Frideric Handel',
    title: 'Messiah — Hallelujah chorus',
    audio: `${UP}/transcoded/9/90/Messiah_Hallelujah_Chorus_1916.ogg/Messiah_Hallelujah_Chorus_1916.ogg.mp3`,
    performer: 'Oratorio Chorus (Edison Diamond Disc, 1916)',
    license: 'public domain',
    scoreNote: 'G. Schirmer 1912 vocal score',
    crop: 0.09,
    cropBottom: 0.09,
    pages: local('hallelujah', 10),
  },
  {
    composer: 'Ludwig van Beethoven',
    title: 'Symphony No. 9 — Finale (Ode to Joy)',
    audio: 'https://archive.org/download/d-842-9-beethoven-9th-i/D842-9%20Beethoven%209th%20%28iv%29.mp3',
    performer: 'Symphony Orchestra & Chorus, cond. Albert Coates (HMV, 1923)',
    license: 'public domain',
    scoreNote: 'Schott first-edition full score, Mainz 1826',
    crop: 0,
    pages: local('odetojoy', 10),
  },
  {
    composer: 'Pyotr Ilyich Tchaikovsky',
    title: 'The Nutcracker — March',
    audio: `${UP}/transcoded/5/53/PDP-CH_-_National_Symphony_Orchestra_of_London_-_Stanford_Robinson%2C_conductor_-_The_Nutcracker_Suite%2C_Op._71_-_Miniature_Overture%2C_March_-_Tchaikovsky_-_Decca-k1142-ar9056.flac/PDP-CH_-_National_Symphony_Orchestra_of_London_-_Stanford_Robinson%2C_conductor_-_The_Nutcracker_Suite%2C_Op._71_-_Miniature_Overture%2C_March_-_Tchaikovsky_-_Decca-k1142-ar9056.flac.mp3`,
    performer: 'National Symphony Orchestra of London, cond. Stanford Robinson (Decca 78 rpm)',
    license: 'public domain',
    scoreNote: 'Eulenburg miniature full score',
    crop: 0.08,
    pages: local('nutcracker', 10),
  },
  {
    composer: 'Edvard Grieg',
    title: 'Morning Mood (Peer Gynt Suite No. 1)',
    audio: `${UP}/transcoded/c/c2/Grieg_-_Peer_Gynt_Suite_No._1%2C_Op._46_-_I._Morning_Mood_%28Musopen_Symphony%29.flac/Grieg_-_Peer_Gynt_Suite_No._1%2C_Op._46_-_I._Morning_Mood_%28Musopen_Symphony%29.flac.mp3`,
    performer: 'Musopen Symphony Orchestra',
    license: 'public domain · Musopen',
    scoreNote: 'C. F. Peters 1888 orchestral full score',
    crop: 0.2,
    pages: local('morningmood', 10),
  },
  {
    composer: 'Gioachino Rossini',
    title: 'William Tell Overture',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/4/43/Gioachino_Rossini%2C_William_Tell_Overture_%28military_band_version%2C_2000%29.ogg/Gioachino_Rossini%2C_William_Tell_Overture_%28military_band_version%2C_2000%29.ogg.mp3',
    performer: 'United States Marine Band',
    license: 'public domain (US federal)',
    scoreNote: 'Breitkopf & Härtel full orchestral score, 1899',
    crop: 0,
    cropBottom: 0.05,
    pages: local('williamtell', 10),
  },
  {
    composer: 'Johann Strauss II',
    title: 'The Blue Danube',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/%22An_der_sch%C3%B6nen%2C_blauen_Donau%22_performed_by_the_U.S._Marine_Band.mp3',
    performer: 'U.S. Marine Band',
    license: 'public domain (US federal)',
    scoreNote: 'Period piano arrangement, Op. 314',
    crop: 0.18,
    pages: local('bluedanube', 9),
  },
  {
    composer: 'Pyotr Ilyich Tchaikovsky',
    title: 'Dance of the Sugar Plum Fairy',
    audio: 'https://ia800404.us.archive.org/29/items/78_dance-of-the-sugar-plum-fairy_tchaikovsky_gbia0546108b/DANCE%20OF%20THE%20SUGAR-PLUM%20FAIRY%20-%20Tchaikovsky.mp3',
    performer: 'orchestra (Children’s Record Guild 78 rpm disc)',
    license: 'public domain',
    scoreNote: 'Eulenburg miniature full score (Nutcracker Suite)',
    crop: 0.09,
    pages: local('sugarplum', 9),
  },
  {
    composer: 'Georges Bizet',
    title: 'Carmen — Prelude',
    audio: `${UP}/transcoded/9/9f/Carmen_-_Prelude_to_Act_1.ogg/Carmen_-_Prelude_to_Act_1.ogg.mp3`,
    performer: 'Musopen (orchestral recording)',
    license: 'public domain · Musopen',
    scoreNote: 'Choudens piano-vocal score, Paris',
    crop: 0,
    pages: local('carmen', 4),
  },
  {
    composer: 'Nikolai Rimsky-Korsakov',
    title: 'Flight of the Bumblebee',
    audio: `${UP}/f/f0/Flight_of_the_Bumblebee_-_Strolling_Strings_-_United_States_Air_Force_Band.mp3`,
    performer: 'Strolling Strings of the U.S. Air Force Band',
    license: 'public domain (US federal)',
    scoreNote: 'Bessel full orchestral score (The Tale of Tsar Saltan)',
    crop: 0,
    pages: local('bumblebee', 10),
  },
  {
    composer: 'Johann Pachelbel',
    title: 'Canon in D',
    audio: `${UP}/transcoded/d/d5/Pachelbel%27s_Canon_per_3_violini_e_basso.ogg/Pachelbel%27s_Canon_per_3_violini_e_basso.ogg.mp3`,
    performer: 'Michael Fischer v. Mollard',
    license: 'CC BY 4.0',
    scoreNote: 'Berlin Staatsbibliothek autograph manuscript',
    crop: 0.06,
    pages: local('canon', 1),
  },
  {
    composer: 'Jacques Offenbach',
    title: 'Orpheus in the Underworld — Can-Can (Galop infernal)',
    audio: `${UP}/transcoded/6/63/Offenbach_-_Orpheus_in_the_Underworld_-_Overture%2C_Can_Can_section.ogg/Offenbach_-_Orpheus_in_the_Underworld_-_Overture%2C_Can_Can_section.ogg.mp3`,
    performer: 'Musopen (orchestral recording)',
    license: 'public domain · Musopen',
    scoreNote: 'Bote & Bock vocal score',
    crop: 0,
    pages: local('cancan', 4),
  },
];

const MEDIUM = [
  {
    composer: 'Johannes Brahms',
    title: 'Hungarian Dance No. 5',
    audio: `${UP}/transcoded/d/d8/Johannes_Brahms_-_Ungarischer_Tanz_5_g-moll.ogg/Johannes_Brahms_-_Ungarischer_Tanz_5_g-moll.ogg.mp3`,
    performer: 'Fulda Symphonic Orchestra, cond. Simon Schindler',
    license: 'EFF OAL 1.0',
    scoreNote: 'Simrock 1876 orchestral full score (Parlow orchestration)',
    crop: 0.24,
    pages: local('hd5', 10),
  },
  {
    composer: 'Claude Debussy',
    title: 'Clair de lune (Suite bergamasque)',
    audio: `${UP}/transcoded/b/be/Clair_de_lune_%28Claude_Debussy%29_Suite_bergamasque.ogg/Clair_de_lune_%28Claude_Debussy%29_Suite_bergamasque.ogg.mp3`,
    performer: 'Laurens Goedhart (piano)',
    license: 'CC BY 3.0',
    scoreNote: 'Fromont Paris edition (BnF scan)',
    crop: 0.27,
    pages: bnf("https://commons.wikimedia.org/wiki/Special:FilePath/Suite%20bergamasque%20(pour%20piano%20par%20Claude%20Debussy)%20-%20btv1b100769278%20({N}%20of%2019).jpg?width=1280", ['10', '11', '12']),
  },
  {
    composer: 'George Frideric Handel',
    title: 'Water Music — Alla Hornpipe',
    audio: `${UP}/transcoded/5/5c/Handel%27s_Water_Music_-_12._Alla_hornpipe_-_Chamber_Orchestra_-_United_States_Marine_Band.opus/Handel%27s_Water_Music_-_12._Alla_hornpipe_-_Chamber_Orchestra_-_United_States_Marine_Band.opus.mp3`,
    performer: 'United States Marine Chamber Orchestra',
    license: 'public domain (US federal)',
    scoreNote: 'Samuel Arnold’s 1788 engraved full score (BnF scan)',
    crop: 0,
    pages: bnf("https://commons.wikimedia.org/wiki/Special:FilePath/The%20celebrated%20Water-musick.%20In%20score.%20Composed%20in%20the%20year%201716.%20By%20G.%20F.%20Handel%20-%20btv1b10072587v%20({N}%20of%2030).jpg?width=1280", ['22', '23']),
  },
  {
    composer: 'Franz Schubert',
    title: 'Ave Maria (Ellens Gesang III, D. 839)',
    audio: `${UP}/transcoded/e/e3/Hmv-db2291-32-4807-2wx766.flac/Hmv-db2291-32-4807-2wx766.flac.mp3`,
    performer: 'Elisabeth Schumann (soprano), orchestra cond. Leo Rosenek (HMV, 1934)',
    license: 'public domain',
    scoreNote: '19th-century “Gems of German Song” edition',
    crop: 0.22,
    pages: pdfPages('c/ca', 'Ave_Maria_%28IA_b10257597%29.pdf', 1280, range(3, 7)),
  },
  {
    composer: 'Franz Liszt',
    title: 'Hungarian Rhapsody No. 2',
    audio: `${UP}/transcoded/2/20/Franz_Liszt_-_Second_Hungarian_Rhapsody.ogg/Franz_Liszt_-_Second_Hungarian_Rhapsody.ogg.mp3`,
    performer: 'Pandora Records (piano)',
    license: 'CC BY-SA 2.0',
    scoreNote: 'Senff first edition',
    crop: 0.3,
    pages: pdfPages('2/28', 'Rhapsodie_hongroise_II._-_pour_le_piano_%28IA_b47693745%29.pdf', 1280, range(2, 9)),
  },
  {
    composer: 'Giuseppe Verdi',
    title: 'La donna è mobile (Rigoletto)',
    audio: `${UP}/transcoded/5/5a/La_Donna_E_Mobile_Rigoletto.ogg/La_Donna_E_Mobile_Rigoletto.ogg.mp3`,
    performer: 'Enrico Caruso (c. 1908 acoustic disc)',
    license: 'public domain',
    scoreNote: 'Ditson libretto-with-airs edition',
    crop: 0.175,
    pages: pdfPages('1/12', 'Verdi%27s_opera_Rigoletto_-_containing_the_Italian_text%2C_with_an_English_translation_and_the_music_of_all_the_principal_airs_%28IA_cu31924082581640%29.pdf', 1280, [25]),
  },
  {
    composer: 'Felix Mendelssohn',
    title: 'Wedding March (A Midsummer Night’s Dream)',
    audio: `${UP}/transcoded/c/cb/A_Midsummer_Night%27s_Dream_Op._61_Wedding_March_%28Mendelssohn%29_European_Archive.ogg/A_Midsummer_Night%27s_Dream_Op._61_Wedding_March_%28Mendelssohn%29_European_Archive.ogg.mp3`,
    performer: 'orchestra, European Archive collection',
    license: 'public domain',
    scoreNote: 'Breitkopf & Härtel orchestral full score',
    crop: 0.12,
    pages: local('weddingmarch', 10),
  },
  {
    composer: 'Camille Saint-Saëns',
    title: 'The Swan (Carnival of the Animals)',
    audio: `${UP}/transcoded/d/db/JOHN_MICHEL_CELLO-SAINT_SAENS_CARNIVAL_OF_ANIMALS_THE_SWAN.ogg/JOHN_MICHEL_CELLO-SAINT_SAENS_CARNIVAL_OF_ANIMALS_THE_SWAN.ogg.mp3`,
    performer: 'John Michel (cello)',
    license: 'CC BY-SA 3.0',
    scoreNote: 'Durand & Schoenewerk 1887 edition',
    crop: 0.29,
    pages: bnf("https://commons.wikimedia.org/wiki/Special:FilePath/Le%20Cygne%2C%20extrait%20du%20Carnaval%20des%20animaux.%20M%C3%A9lodie%20pour%20violoncelle%20et%20piano%20par%20C.%20Saint-Sa%C3%ABns...%20-%20bpt6k319529z%20({N}%20of%2012).jpg?width=1280", ['03']),
  },
  {
    composer: 'Robert Schumann',
    title: 'Träumerei (Kinderszenen, Op. 15 No. 7)',
    audio: `${UP}/transcoded/0/06/Robert_Schumann_-_scenes_from_childhood%2C_op._15_-_vii._dreaming.ogg/Robert_Schumann_-_scenes_from_childhood%2C_op._15_-_vii._dreaming.ogg.mp3`,
    performer: 'piano, Musopen recording',
    license: 'public domain · Musopen',
    scoreNote: 'Balmer & Weber “Salon and Concert” edition',
    crop: 0.16,
    pages: pdfPages('8/8a', 'Tr%C3%A4umerei_-_reverie_%3B_Romanze_%28IA_b10005511%29.pdf', 1280, [2]),
  },
  {
    composer: 'Frédéric Chopin',
    title: 'Nocturne in E-flat major, Op. 9 No. 2',
    audio: `${UP}/8/82/Nocturne_in_E_flat_major%2C_Op._9_no._2.mp3`,
    performer: 'Frank Levy (piano)',
    license: 'public domain · Musopen',
    scoreNote: 'Kistner first edition, 1832',
    crop: 0.16,
    pages: local('nocturne92', 2),
  },
  {
    composer: 'Johann Sebastian Bach',
    title: 'Cello Suite No. 1 in G major — Prélude',
    audio: `${UP}/transcoded/4/43/JOHN_MICHEL_CELLO-J_S_BACH_CELLO_SUITE_1_in_G_Prelude.ogg/JOHN_MICHEL_CELLO-J_S_BACH_CELLO_SUITE_1_in_G_Prelude.ogg.mp3`,
    performer: 'John Michel (cello)',
    license: 'CC BY-SA 3.0',
    scoreNote: 'Grützmacher edition, C. F. Peters',
    crop: 0.18,
    pages: local('cellosuite1', 1),
  },
  {
    composer: 'Franz Liszt',
    title: 'Liebestraum No. 3 in A-flat major',
    audio: `${UP}/transcoded/0/02/Franz_Liszt_-_Liebestraum%2C_Ab_Major.ogg/Franz_Liszt_-_Liebestraum%2C_Ab_Major.ogg.mp3`,
    performer: 'Martha Goldstein (piano)',
    license: 'CC BY-SA 2.0',
    scoreNote: 'G. Schirmer 1900 edition',
    crop: 0.12,
    pages: local('liebestraum', 6),
  },
  {
    composer: 'Pyotr Ilyich Tchaikovsky',
    title: 'Piano Concerto No. 1 in B-flat minor — I.',
    audio: `${UP}/transcoded/4/48/Tchaikovsky%2C_Concerto_No.1_in_B-flat_minor_Op.23%2C_I._Allegro.ogg/Tchaikovsky%2C_Concerto_No.1_in_B-flat_minor_Op.23%2C_I._Allegro.ogg.mp3`,
    performer: 'Musopen collection (piano and orchestra)',
    license: 'CC0',
    scoreNote: 'Breitkopf two-piano edition',
    crop: 0.12,
    pages: local('tchaikpc1', 10),
  },
  {
    composer: 'George Gershwin',
    title: 'Rhapsody in Blue',
    audio: 'https://archive.org/download/1st-recording-of-rhapsody-in-blue-paul-whiteman-orch.-george-gershwin-piano-1924-version/1st%20RECORDING%20OF_%20Rhapsody%20In%20Blue%20-%20Paul%20Whiteman%20Orch.%20%26%20George%20Gershwin%20piano%20%281924%20version%29.mp3',
    performer: 'Paul Whiteman Orchestra with George Gershwin at the piano (1924)',
    license: 'public domain',
    scoreNote: 'New World Music 1924 piano edition (Gershwin’s own arrangement)',
    crop: 0.16,
    pages: local('rhapsodyblue', 10),
  },
  {
    composer: 'Wolfgang Amadeus Mozart',
    title: 'Symphony No. 40 in G minor — I. Molto allegro',
    audio: `${UP}/transcoded/a/a8/Mozart_-_Symphony_No._40_in_G_minor%2C_K550_-_I._Molto_allegro_%28Musopen_Symphony%29.flac/Mozart_-_Symphony_No._40_in_G_minor%2C_K550_-_I._Molto_allegro_%28Musopen_Symphony%29.flac.mp3`,
    performer: 'Musopen Symphony Orchestra',
    license: 'public domain · Musopen',
    scoreNote: 'Sieber 1803 first-edition orchestral part (Violino I)',
    crop: 0.15,
    pages: local('mozart40', 2),
  },
  {
    composer: 'Wolfgang Amadeus Mozart',
    title: 'The Marriage of Figaro — Overture',
    audio: `${UP}/transcoded/9/9d/Wolfgang_Amadeus_Mozart_-_US_ARMY_-_Mozart_overture_to_the_marriage_of_figaro.ogg/Wolfgang_Amadeus_Mozart_-_US_ARMY_-_Mozart_overture_to_the_marriage_of_figaro.ogg.mp3`,
    performer: 'The United States Army Band',
    license: 'public domain (US federal)',
    scoreNote: 'Breitkopf 1879 orchestral full score',
    crop: 0.33,
    cropBottom: 0.07,
    pages: local('figaro', 10),
  },
  {
    composer: 'Franz Schubert',
    title: 'Marche militaire No. 1',
    audio: `${UP}/transcoded/1/1c/PDP-CH_-_San_Francisco_Symphony_-_Alfred_Hertz_-_Marche_Militaire_-_Franz_Schubert_-_Hmv-d1286-5-0601.flac/PDP-CH_-_San_Francisco_Symphony_-_Alfred_Hertz_-_Marche_Militaire_-_Franz_Schubert_-_Hmv-d1286-5-0601.flac.mp3`,
    performer: 'San Francisco Symphony, cond. Alfred Hertz (HMV disc, 1920s)',
    license: 'public domain',
    scoreNote: 'Breitkopf 1888 piano four-hands original',
    crop: 0.3,
    pages: local('militaire', 6),
  },
  {
    composer: 'Johann Sebastian Bach',
    title: 'Air on the G String (Orchestral Suite No. 3)',
    audio: `${UP}/e/ec/Air_-_Air_Force_Strings_-_United_States_Air_Force_Band.mp3`,
    performer: 'Air Force Strings of the U.S. Air Force Band',
    license: 'public domain (US federal)',
    scoreNote: 'Bach-Gesellschaft 1885 full score',
    crop: 0,
    pages: local('airgstring', 2),
  },
  {
    composer: 'Gustav Holst',
    title: 'The Planets — IV. Jupiter',
    audio: 'https://archive.org/download/holst-the-planets-holst-london-symphony-orchestra-1922-1924/The%20Planets%20Op.%2032%2C%20H.%20125_%20IV.%20Jupiter%2C%20The%20Bringer%20of%20Jollity.mp3',
    performer: 'London Symphony Orchestra conducted by the composer himself (1922–24)',
    license: 'public domain',
    scoreNote: 'Goodwin & Tabb 1921 full score',
    crop: 0.09,
    pages: local('jupiter', 10),
  },
  {
    composer: 'Pyotr Ilyich Tchaikovsky',
    title: '1812 Overture',
    audio: `${UP}/transcoded/6/66/1812_Overture_-_United_States_Marine_Band.opus/1812_Overture_-_United_States_Marine_Band.opus.mp3`,
    performer: '“The President’s Own” U.S. Marine Band, live 2019',
    license: 'public domain (US federal)',
    scoreNote: 'Jurgenson 1882 orchestral full score',
    crop: 0.11,
    pages: local('1812', 10),
  },
  {
    composer: 'Edward Elgar',
    title: 'Pomp and Circumstance March No. 1',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/2/28/ELGAR_Pomp_and_Circumstance_in_D%2C_Opus_39%2C_No._1_-_United_States_Marine_Band.mp3',
    performer: 'United States Marine Band',
    license: 'public domain (US federal)',
    scoreNote: 'Boosey full orchestral score',
    crop: 0.17,
    pages: local('pomp', 10),
  },
  {
    composer: 'Bedřich Smetana',
    title: 'The Moldau',
    audio: `${UP}/transcoded/3/39/Smetana%2C_M%C3%A1_vlast_-_Vltava_-_The_Moldau.ogg/Smetana%2C_M%C3%A1_vlast_-_Vltava_-_The_Moldau.ogg.mp3`,
    performer: 'Musopen Symphony Orchestra',
    license: 'CC0 · Musopen',
    scoreNote: 'Eulenburg miniature full score, 1914',
    crop: 0.14,
    pages: local('moldau', 10),
  },
  {
    composer: 'Claude Debussy',
    title: 'Arabesque No. 1',
    audio: `${UP}/transcoded/0/0f/Claude_Debussy_-_Premi%C3%A8re_Arabesque_-_Patrizia_Prati.ogg/Claude_Debussy_-_Premi%C3%A8re_Arabesque_-_Patrizia_Prati.ogg.mp3`,
    performer: 'Patrizia Prati (piano)',
    license: 'CC BY-SA 4.0',
    scoreNote: 'Durand first edition, 1904',
    crop: 0.25,
    pages: local('arabesque', 5),
  },
  {
    composer: 'Jean Sibelius',
    title: 'Finlandia',
    audio: 'https://archive.org/download/finlandia-victor-acoustic/Finlandia_Victor-acoustic.mp3',
    performer: "Conway's Band (Victor acoustic disc, 1915)",
    license: 'public domain',
    scoreNote: 'Breitkopf & Härtel full orchestral score',
    crop: 0.11,
    pages: local('finlandia', 10),
  },
  {
    composer: 'Modest Mussorgsky',
    title: 'Night on Bald Mountain',
    audio: `${UP}/transcoded/c/ca/Modest_Mussorgsky_-_night_on_bald_mountain.ogg/Modest_Mussorgsky_-_night_on_bald_mountain.ogg.mp3`,
    performer: 'Musopen Symphony Orchestra',
    license: 'public domain · Musopen',
    scoreNote: 'V. Bessel & Co. 1886 full score (Rimsky-Korsakov orchestration)',
    crop: 0.2,
    pages: local('baldmountain', 10),
  },
  {
    composer: 'Johann Sebastian Bach',
    title: 'Brandenburg Concerto No. 3 — I. Allegro',
    audio: `${UP}/transcoded/b/b0/Bach_-_Brandenburg_Concerto_No._3_-_1._Allegro.ogg/Bach_-_Brandenburg_Concerto_No._3_-_1._Allegro.ogg.mp3`,
    performer: 'live concert recording (Al Goldstein Collection)',
    license: 'CC BY-SA 2.0',
    scoreNote: 'Bach-Gesellschaft full score (Breitkopf & Härtel, 1871)',
    crop: 0.15,
    pages: local('brandenburg3', 10),
  },
  {
    composer: 'Ludwig van Beethoven',
    title: 'Symphony No. 7 — II. Allegretto',
    audio: 'https://archive.org/download/BeethovenSymphonyNo.7_807/02_Beethoven_Sym_No.7_m2.mp3',
    performer: 'Musopen orchestral recording',
    license: 'public domain · Musopen',
    scoreNote: 'Breitkopf & Härtel Werke full orchestral score',
    crop: 0,
    pages: local('beethoven7', 10),
  },
  {
    composer: 'Frédéric Chopin',
    title: 'Fantaisie-Impromptu, Op. 66',
    audio: `${UP}/transcoded/4/44/Muriel-Nguyen-Xuan-Chopin-fantaisie-impromptu-opus66.ogg/Muriel-Nguyen-Xuan-Chopin-fantaisie-impromptu-opus66.ogg.mp3`,
    performer: 'Muriel Nguyen Xuan (piano)',
    license: 'CC BY-SA 4.0',
    scoreNote: 'Fontana first edition, Paris 1855',
    crop: 0.28,
    pages: local('fantaisieimpromptu', 9),
  },
  {
    composer: 'Wolfgang Amadeus Mozart',
    title: 'Lacrimosa (Requiem, K. 626)',
    audio: `${UP}/transcoded/5/5b/W._A._Mozart_-_Requiem%2C_K._626_%28Bruno_Walter%2C_Wiener_Philharmoniker%2C_Wiener_Staatsopernchor%2C_1956%29_-_08._Lacrimosa.ogg/W._A._Mozart_-_Requiem%2C_K._626_%28Bruno_Walter%2C_Wiener_Philharmoniker%2C_Wiener_Staatsopernchor%2C_1956%29_-_08._Lacrimosa.ogg.mp3`,
    performer: 'Bruno Walter, Wiener Philharmoniker & Staatsopernchor (1956)',
    license: 'public domain',
    scoreNote: 'Breitkopf & Härtel full score (Alte Mozart-Ausgabe)',
    crop: 0.1,
    pages: local('lacrimosa', 6),
  },
  {
    composer: 'Gioachino Rossini',
    title: 'The Barber of Seville — Overture',
    audio: 'https://archive.org/download/78_overture-to-barber-of-seville_palace-guards-band-rossini_gbia3034692b/OVERTURE%20TO%20%22BARBER%20OF%20SEVILLE%20-%20PALACE%20GUARDS%20BAND.mp3',
    performer: 'Palace Guards Band (acoustic 78, 1910)',
    license: 'public domain',
    scoreNote: 'Philharmonia miniature full score, Vienna 1920',
    crop: 0.21,
    pages: local('barber', 10),
  },
  {
    composer: 'Jacques Offenbach',
    title: 'Barcarolle (The Tales of Hoffmann)',
    audio: 'https://archive.org/download/78_barcarolle-the-tales-of-hoffmann_american-symphony-orchestra-j-offenbach_gbia0165471b/Barcarolle-%20The%20Tales%20of%20Hof%20-%20American%20Symphony%20Orchestra.mp3',
    performer: 'American Symphony Orchestra (acoustic 78, 1915)',
    license: 'public domain',
    scoreNote: 'Choudens full orchestral score, Paris',
    crop: 0.12,
    pages: local('barcarolle', 8),
  },
  {
    composer: 'George Frideric Handel',
    title: 'Sarabande in D minor, HWV 437',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/c/ca/Handel_-_Suite_Vol._2_No._4_in_D_minor_HWV_437_%28Constantin_Stephan%29.oga/Handel_-_Suite_Vol._2_No._4_in_D_minor_HWV_437_%28Constantin_Stephan%29.oga.mp3',
    performer: 'Constantin Stephan (harpsichord)',
    license: 'CC BY-SA 4.0',
    scoreNote: 'Händel-Gesellschaft edition (Chrysander, Leipzig 1859)',
    crop: 0,
    pages: local('sarabande', 2),
  },
  {
    composer: 'Edvard Grieg',
    title: 'Piano Concerto in A minor, Op. 16 — I. Allegro molto moderato',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/3/3a/Edvard_Grieg_-_Concerto_in_A_minor%2C_1st_movement.ogg/Edvard_Grieg_-_Concerto_in_A_minor%2C_1st_movement.ogg.mp3',
    performer: "Neal O'Doan (piano), University of Washington Symphony",
    license: 'CC BY-SA 2.0',
    scoreNote: 'C. F. Peters full orchestral score, Leipzig (ca. 1910)',
    crop: 0.09,
    pages: local('griegconcerto', 8),
  },
  {
    composer: 'Antonio Vivaldi',
    title: 'The Four Seasons — “Summer”, RV 315, III. Presto',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/f/fa/Vivaldi_-_Four_Seasons_2_Summer_mvt_3_Presto_-_John_Harrison_violin.oga/Vivaldi_-_Four_Seasons_2_Summer_mvt_3_Presto_-_John_Harrison_violin.oga.mp3',
    performer: 'John Harrison (violin), Wichita State University Chamber Players',
    license: 'CC BY-SA 3.0',
    scoreNote: '1725 first-edition part book (BnF scan)',
    crop: 0.18,
    pages: local('summer', 2),
  },
  {
    composer: 'Domenico Scarlatti',
    title: 'Keyboard Sonata in E major, K. 380',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/6/6e/Scarlatti_Sonata_E_Major_K380.ogg/Scarlatti_Sonata_E_Major_K380.ogg.mp3',
    performer: 'Raymond Smullyan (piano)',
    license: 'Audio: CC BY-SA 2.0 (Raymond Smullyan, via Piano Society / Wikimedia Commons). Score: Public Domain.',
    scoreNote: 'Longo edition, ed. Alessandro Longo — "Opere complete per clavicembalo," Vol.1, pp.78-81 (sonata L.23). Milan: G. Ricordi & C., 1906. Plate E.R. 541. Engraved scan, IMSLP #691879.',
    crop: 0,
    pages: local('scarlatti', 4),
  },
  {
    composer: 'Max Bruch',
    title: 'Violin Concerto No. 1 in G minor, Op. 26 — I. Vorspiel',
    audio: 'https://archive.org/download/78_concerto-no-1-in-g-minor-1st-movement-1st-record_master-yehudi-menuhin-and-the-lond_gbia7042538a/-%20MASTER%20YEHUDI%20MENUHIN%20and%20the%20London%20Symphony%20Orchestra.mp3',
    performer: 'Yehudi Menuhin (violin), London Symphony Orchestra, cond. Sir Landon Ronald (HMV, 1931)',
    license: 'public domain',
    scoreNote: 'Ernst Eulenburg miniature full orchestral score (engraved), from IMSLP',
    crop: 0.11,
    pages: local('bruch', 10),
  },
  {
    composer: 'Wolfgang Amadeus Mozart',
    title: 'Clarinet Concerto in A major, K. 622 — II. Adagio',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/9/99/Wolfgang_Amadeus_Mozart_-_Clarinet_Concerto_-_2._Adagio.ogg/Wolfgang_Amadeus_Mozart_-_Clarinet_Concerto_-_2._Adagio.ogg.mp3',
    performer: 'William McColl (clarinet), University of Washington Symphony Orchestra, Abraham Kaplan conducting (rec. Dec 1987)',
    license: 'CC BY-SA 2.0',
    scoreNote: 'Breitkopf & Härtel 1881 full score (Mozarts Werke, Serie XII, Bd.2, ed. Ernst Rudorff), plate W.A.M. 622',
    crop: 0.07,
    pages: local('clarinetconcerto', 6),
  },
  {
    composer: 'Antonio Vivaldi',
    title: 'The Four Seasons — “Autumn”, RV 293, I. Allegro',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/0/0f/Vivaldi_-_Four_Seasons_3_Autumn_mvt_1_Allegro_-_John_Harrison_violin.oga/Vivaldi_-_Four_Seasons_3_Autumn_mvt_1_Allegro_-_John_Harrison_violin.oga.mp3',
    performer: 'John Harrison (violin), Wichita State University Chamber Players',
    license: 'CC BY-SA 3.0',
    scoreNote: '1725 first-edition part book (Violino Principale, BnF scan)',
    crop: 0.2,
    pages: local('autumn', 2),
  },
  {
    composer: 'George Frideric Handel',
    title: 'Arrival of the Queen of Sheba (Solomon)',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2d/Handel_-_Arrival_of_the_Queen_of_Sheba.ogg/Handel_-_Arrival_of_the_Queen_of_Sheba.ogg.mp3',
    performer: 'Advent Chamber Orchestra, dir. Roxanna Pavel Goldstein (Nov 2006)',
    license: 'CC BY-SA 2.0 (audio); score public domain',
    scoreNote: 'Georg Friedrich Händels Werke, Band 26 (Solomon), ed. Friedrich Chrysander — Leipzig: Deutsche Händel-Gesellschaft, 1867; plate H.W. 26. Engraved scan by Bayerische Staatsbibliothek (D-Mbs), IMSLP #18850.',
    crop: 0.18,
    pages: local('sheba', 6),
  },
  {
    composer: 'Sergei Rachmaninoff',
    title: 'Vocalise, Op. 34 No. 14',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2c/Rachmaninoff_-_Vocalise_transcribed_for_Violin_and_Piano.ogg/Rachmaninoff_-_Vocalise_transcribed_for_Violin_and_Piano.ogg.mp3',
    performer: 'Roxana Pavel Goldstein (violin), Monica Pavel (piano)',
    license: 'CC BY-SA 2.0',
    scoreNote: "Hawkes & Son 1919 full orchestral score (composer's own orchestration)",
    crop: 0.2,
    pages: local('paganinirhapsody', 10),
  },
];

const HARD = [
  {
    composer: 'Niccolò Paganini',
    title: 'Caprice No. 24 in A minor',
    audio: `${UP}/transcoded/3/3e/Paganini_-_Caprice_in_A_minor%2C_Op._1%2C_No._24_%28Menuhin%2C_Baller%29.flac/Paganini_-_Caprice_in_A_minor%2C_Op._1%2C_No._24_%28Menuhin%2C_Baller%29.flac.mp3`,
    performer: 'Yehudi Menuhin (violin), Adolph Baller (piano), 1948',
    license: 'public domain',
    scoreNote: 'Schonenberger Paris edition (BnF scan)',
    crop: 0.24,
    pages: bnf("https://commons.wikimedia.org/wiki/Special:FilePath/24%20Caprices%20ou%20etudes%20pour%20violon...%20par%20N.%20Paganini....%20Op.%201...%20-%20btv1b10071191q%20({N}%20of%2055).jpg?width=1280", ['52', '53', '54']),
  },
  {
    composer: 'Giacomo Puccini',
    title: 'Sì, mi chiamano Mimì (La bohème)',
    audio: `${UP}/transcoded/a/a1/Puccini_Mi_chiamano_Mim%C3%AC_par_Claudia_Muzio.ogg/Puccini_Mi_chiamano_Mim%C3%AC_par_Claudia_Muzio.ogg.mp3`,
    performer: 'Claudia Muzio (soprano), 1911 disc',
    license: 'public domain',
    scoreNote: 'French vocal score (BnF scan)',
    crop: 0.08,
    pages: bnf("https://commons.wikimedia.org/wiki/Special:FilePath/La%20Boh%C3%A8me%20-%204%20actes%20de%20MM.%20Giacosa%20et%20L.%20Illica%20%3B%20version%20fran%C3%A7aise%20de%20Paul%20Ferrier%20%3B%20musique%20de%20Giacomo%20Puccini%20%3B%20partition%20chant%20et%20piano%2C%20arrangement%20de%20C.%20Carignani%20-%20bpt6k329584c%20({N}%20of%20300).jpg?width=1280", ['082', '083', '084', '085', '086', '087']),
  },
  {
    composer: 'Gustav Mahler',
    title: 'Symphony No. 5 — IV. Adagietto',
    audio: `${UP}/transcoded/b/b2/Mahler_Symphony_No._5%2C_IV._Adagietto.ogg/Mahler_Symphony_No._5%2C_IV._Adagietto.ogg.mp3`,
    performer: 'Peabody Symphony Orchestra',
    license: 'CC0',
    scoreNote: 'Peters 1904 first-edition full score',
    crop: 0.13,
    pages: pdfPages('2/23', 'Symphonie_No._5%2C_f%C3%BCr_grosses_Orchester_%28IA_agn4674.0001.001.umich.edu%29.pdf', 1280, range(180, 184)),
  },
  {
    composer: 'Edvard Grieg',
    title: 'Holberg Suite — I. Praeludium',
    audio: `${UP}/0/08/Grieg%27s_Suite_for_Strings%2C_Op._40%2C_%22From_Holberg%E2%80%99s_Time%22_-_I._Praeludium_-_Chamber_Orchestra_-_United_States_Marine_Band.mp3`,
    performer: 'U.S. Marine Band Chamber Orchestra',
    license: 'public domain (US federal)',
    scoreNote: 'Peters string-orchestra edition (original scoring)',
    crop: 0.12,
    pages: local('holberg', 5),
  },
  {
    composer: 'Johann Sebastian Bach',
    title: 'Passacaglia and Fugue in C minor, BWV 582',
    audio: `${UP}/9/92/1009-Bach-Passacaglia_c-moll_582.mp3`,
    performer: 'Andreas Arand, Klais organ, Kreuzbergkirche Bonn (1985)',
    license: 'CC BY-SA 4.0',
    scoreNote: 'Bach-Gesellschaft 1867 edition, organ score',
    crop: 0.1,
    cropBottom: 0.08, // edition footer "B.W. XV." would leak the composer
    pages: local('passacaglia', 10),
  },
  {
    composer: 'Ludwig van Beethoven',
    title: 'Egmont Overture, Op. 84',
    audio: `${UP}/transcoded/8/85/Beethoven_-_Egmont_Overture%2C_Op._84_%28Musopen_Symphony%29.flac/Beethoven_-_Egmont_Overture%2C_Op._84_%28Musopen_Symphony%29.flac.mp3`,
    performer: 'Musopen Symphony Orchestra',
    license: 'public domain · Musopen',
    scoreNote: 'Cranz piano four-hands edition',
    crop: 0.15,
    pages: pdfPages('5/56', 'Ouverture_c%C3%A9l%C3%A8bre_de_la_trag%C3%A9die-_Egmont_-_op._84_%28IA_b30176591%29.pdf', 1280, range(2, 9)),
  },
  {
    composer: 'Antonín Dvořák',
    title: 'Slavonic Dance in E minor, Op. 72 No. 2',
    audio: `${UP}/9/95/Slavonic_Dance_No._2_-_Strolling_Strings_-_United_States_Air_Force_Band.mp3`,
    performer: 'Strolling Strings of the U.S. Air Force Band',
    license: 'public domain (US federal)',
    scoreNote: 'Simrock 1881 orchestral full score',
    crop: 0,
    pages: local('slavonic722', 10),
  },
  {
    composer: 'Camille Saint-Saëns',
    title: 'Danse macabre, Op. 40',
    audio: `${UP}/transcoded/8/8b/Saint-Sa%C3%ABns_-_Danse_macabre_%28Fourestier%2C_1953%29.flac/Saint-Sa%C3%ABns_-_Danse_macabre_%28Fourestier%2C_1953%29.flac.mp3`,
    performer: 'Orchestre des Concerts Colonne, cond. Louis Fourestier (1953)',
    license: 'public domain (BnF)',
    scoreNote: 'Durand orchestral full score',
    crop: 0.17,
    pages: local('dansemacabre', 10),
  },
  {
    composer: 'Sergei Rachmaninoff',
    title: 'Prelude in C-sharp minor, Op. 3 No. 2',
    audio: `${UP}/transcoded/b/b9/Sergei_Rachmaninoff_performs_Rachmaninoff%27s_Prelude_in_C_sharp_minor%2C_Op._3.ogg/Sergei_Rachmaninoff_performs_Rachmaninoff%27s_Prelude_in_C_sharp_minor%2C_Op._3.ogg.mp3`,
    performer: 'the composer himself (Edison recording, 1919)',
    license: 'public domain',
    scoreNote: 'Bosworth / B. F. Wood 1896 edition',
    crop: 0.13,
    pages: local('rachprelude', 5),
  },
  {
    composer: 'Franz Schubert',
    title: 'Symphony No. 8 “Unfinished” — I. Allegro moderato',
    audio: `${UP}/transcoded/9/96/Schubert_Symphony_No._8_%27Unfinished%27_-_1-_Allegro_moderato_in_B_minor.ogg/Schubert_Symphony_No._8_%27Unfinished%27_-_1-_Allegro_moderato_in_B_minor.ogg.mp3`,
    performer: 'Fulda Symphonic Orchestra',
    license: 'EFF OAL 1.0',
    scoreNote: 'Breitkopf 1885 full score — Sir Henry Wood’s marked conducting copy',
    crop: 0.3,
    pages: local('unfinished', 10),
  },
  {
    composer: 'Antonio Vivaldi',
    title: 'The Four Seasons — “Winter”, RV 297, I.',
    audio: `${UP}/transcoded/2/2a/Vivaldi_-_Four_Seasons_4_Winter_mvt_1_Allegro_non_molto_-_John_Harrison_violin.oga/Vivaldi_-_Four_Seasons_4_Winter_mvt_1_Allegro_non_molto_-_John_Harrison_violin.oga.mp3`,
    performer: 'John Harrison (violin), Wichita State University Chamber Players',
    license: 'CC BY-SA 3.0',
    scoreNote: '1725 first-edition part book (Violino Principale, BnF scan)',
    crop: 0.18,
    pages: local('winter', 4),
  },
  {
    composer: 'Giuseppe Verdi',
    title: 'Anvil Chorus (Il trovatore)',
    audio: `${UP}/9/9a/%22Vedi%21_Le_Fosche%22_from_Il_Trovatore_-_Singing_Sergeants_-_United_States_Air_Force_Band.mp3`,
    performer: 'Singing Sergeants & Concert Band of the U.S. Air Force',
    license: 'public domain (US federal)',
    scoreNote: 'Novello/Ditson 1870 vocal score',
    crop: 0.21,
    cropBottom: 0.1, // page footer names the opera and composer
    pages: local('anvil', 9),
  },
  {
    composer: 'Hector Berlioz',
    title: 'Symphonie fantastique — IV. March to the Scaffold',
    audio: `${UP}/transcoded/b/b9/Hector_Berlioz_-_Symphonie_fantastique%2C_op._14_-_4._Marche_au_supplice_%28Igor_Markevitch%2C_Orchestre_Lamoureux%2C_1962%29.flac/Hector_Berlioz_-_Symphonie_fantastique%2C_op._14_-_4._Marche_au_supplice_%28Igor_Markevitch%2C_Orchestre_Lamoureux%2C_1962%29.flac.mp3`,
    performer: 'Orchestre Lamoureux, cond. Igor Markevitch (1962)',
    license: 'public domain',
    scoreNote: 'Breitkopf & Härtel full orchestral score, 1900',
    crop: 0.11,
    cropBottom: 0.06, // bottom footnote plate "H.B.1"
    pages: local('symphoniefantastique', 10),
  },
  {
    composer: 'Gabriel Fauré',
    title: 'Pavane, Op. 50',
    audio: 'https://archive.org/download/FAUREPavaneOp.50/Faur-PavaneOp.50.mp3',
    performer: 'cond. Sir Malcolm Sargent',
    license: 'CC BY-NC-SA 3.0',
    scoreNote: 'Hamelle full orchestral score',
    crop: 0.13,
    pages: local('pavane', 10),
  },
  {
    composer: 'Maurice Ravel',
    title: 'Pavane pour une infante défunte',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/d/d6/Maurice_Ravel_-_Th%C3%A9r%C3%A8se_Dussaut_-_Pavane_pour_une_infante_d%C3%A9funte.ogg/Maurice_Ravel_-_Th%C3%A9r%C3%A8se_Dussaut_-_Pavane_pour_une_infante_d%C3%A9funte.ogg.mp3',
    performer: 'Thérèse Dussaut (piano)',
    license: 'CC BY-SA 2.0',
    scoreNote: 'E. Demets / Max Eschig piano edition, Paris 1921',
    crop: 0.27,
    pages: local('ravelpavane', 5),
  },
  {
    composer: 'Igor Stravinsky',
    title: 'The Firebird — Infernal Dance',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/a/ab/Infernal_Dance_from_The_Firebird_by_Stravinsky.ogg/Infernal_Dance_from_The_Firebird_by_Stravinsky.ogg.mp3',
    performer: '“The President’s Own” United States Marine Band',
    license: 'public domain (US federal)',
    scoreNote: 'P. Jurgenson full orchestral score, Moscow 1910 (original ballet)',
    crop: 0.07,
    pages: local('firebird', 10),
  },
  {
    composer: 'Sergei Prokofiev',
    title: 'March from The Love for Three Oranges, Op. 33',
    audio: 'https://archive.org/download/Love_for_Three_Oranges/threeoranges.mp3',
    performer: 'violin & piano (Heifetz arrangement)',
    license: 'CC BY-NC-ND 2.5',
    scoreNote: 'Muzyka full score of the Op. 33 bis Suite (1922 Gutheil engraving)',
    crop: 0.05,
    cropBottom: 0.06,
    pages: local('threeoranges', 10),
  },
  {
    composer: 'Edward Elgar',
    title: 'Enigma Variations — IX. Nimrod',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e7/Elgar%3B_Enigma_variations%2C_Theme_IX._Nimrod.ogg/Elgar%3B_Enigma_variations%2C_Theme_IX._Nimrod.ogg.mp3',
    performer: 'Hallé Orchestra, cond. John Barbirolli (HMV, 1947)',
    license: 'public domain',
    scoreNote: 'Novello & Co. full orchestral score, 1899',
    crop: 0.08,
    pages: local('nimrod', 5),
  },
  {
    composer: 'Jean Sibelius',
    title: 'Valse triste, Op. 44',
    audio: 'https://archive.org/download/NikolaiSOKOLOFFConductsTheCLEVELANDORCHESTRA/04.Sibelius-ValseTristeOp.40.mp3',
    performer: 'Cleveland Orchestra, Nikolai Sokoloff (Brunswick 78, 1924)',
    license: 'public domain',
    scoreNote: 'Breitkopf & Härtel full orchestral score, Leipzig 1904',
    crop: 0.2,
    pages: local('valsetriste', 10),
  },
  {
    composer: 'Franz Liszt',
    title: 'Mephisto Waltz No. 1',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/7/79/Franz_Liszt_Mephisto_Waltz_No._1.ogg/Franz_Liszt_Mephisto_Waltz_No._1.ogg.mp3',
    performer: 'Giorgi Latso (piano)',
    license: 'CC BY-SA 4.0',
    scoreNote: "Bote & Bock 1917 edition (ed. d'Albert)",
    crop: 0.24,
    pages: local('mephisto', 10),
  },
  {
    composer: 'Felix Mendelssohn',
    title: 'The Hebrides (Fingal’s Cave) Overture, Op. 26',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/9/96/Mendelssohn_-_Hebrides_Overture_Fingal%27s_Cave.ogg/Mendelssohn_-_Hebrides_Overture_Fingal%27s_Cave.ogg.mp3',
    performer: 'Musopen Symphony Orchestra',
    license: 'public domain · Musopen',
    scoreNote: 'Breitkopf & Härtel first-edition full score, Leipzig 1834',
    crop: 0.15,
    pages: local('hebrides', 10),
  },
  {
    composer: 'Nikolai Rimsky-Korsakov',
    title: 'Scheherazade, Op. 35 — I. The Sea and Sinbad’s Ship',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/4/4e/Rimsky-Korsakov._Scheherazade%2C_Symphonic_Suite%2C_Op._35_-_01_The_Sea_And_Sinbads_Ship.ogg/Rimsky-Korsakov._Scheherazade%2C_Symphonic_Suite%2C_Op._35_-_01_The_Sea_And_Sinbads_Ship.ogg.mp3',
    performer: 'San Francisco Symphony, Pierre Monteux (Victor, 1942)',
    license: 'public domain (CC0)',
    scoreNote: 'Ernst Eulenburg miniature full score (early-20th-c. engraving)',
    crop: 0.15,
    pages: local('scheherazade', 10),
  },
  {
    composer: 'Richard Wagner',
    title: 'Tannhäuser — Overture',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/d/d5/Overture_to_Tannhauser_-_U.S._Marine_Band.ogg/Overture_to_Tannhauser_-_U.S._Marine_Band.ogg.mp3',
    performer: '“The President’s Own” United States Marine Band',
    license: 'public domain (US federal)',
    scoreNote: 'Adolph Fürstner orchestral full score, Berlin (19th-c. engraving)',
    crop: 0.36,
    pages: local('tannhauser', 10),
  },
  {
    composer: 'Antonín Dvořák',
    title: 'Carnival Overture, Op. 92',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b8/Antonin_Dvorak_-_carnival_overture%2C_op._92.ogg/Antonin_Dvorak_-_carnival_overture%2C_op._92.ogg.mp3',
    performer: 'Wind band (Musopen, 2006)',
    license: 'public domain · Musopen',
    scoreNote: 'N. Simrock first-edition full score, Berlin 1894',
    crop: 0.12,
    pages: local('carnival', 10),
  },
  {
    composer: 'Johannes Brahms',
    title: 'Symphony No. 3 in F major, Op. 90 — III. Poco allegretto',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b9/Brahms%2C_Symphony_No._3_in_F_Major%2C_Op._90_-_III._Poco_allegretto.ogg/Brahms%2C_Symphony_No._3_in_F_Major%2C_Op._90_-_III._Poco_allegretto.ogg.mp3',
    performer: 'Musopen Symphony Orchestra',
    license: 'public domain · Musopen',
    scoreNote: 'N. Simrock first-edition full score, Berlin 1884',
    crop: 0.12,
    pages: local('brahms3', 10),
  },
  {
    composer: 'Camille Saint-Saëns',
    title: 'Bacchanale (Samson et Dalila)',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Danse_Bacchanale_-_Concert_Band_-_United_States_Air_Force_Band.mp3',
    performer: 'The United States Air Force Band',
    license: 'public domain (US federal)',
    scoreNote: 'Durand, Schoenewerk & Cie full orchestral score, Paris 1878',
    crop: 0.17,
    pages: local('bacchanale', 10),
  },
  {
    composer: 'Jean-Baptiste Lully',
    title: 'Marche pour la cérémonie des Turcs',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/7/76/Lully_Le_Bourgeois_Gentilhomme_-_11._Marche_pour_la_Ceremonie_des_Turcs.ogg/Lully_Le_Bourgeois_Gentilhomme_-_11._Marche_pour_la_Ceremonie_des_Turcs.ogg.mp3',
    performer: 'Advent Chamber Orchestra',
    license: 'Audio: CC BY-SA 2.0 (Advent Chamber Orchestra). Score: public domain.',
    scoreNote: 'Full score ed. J.-B. Weckerlin, "Le Bourgeois gentilhomme" (comédie-ballet), pre-1930 engraving (Michaelis "Chefs-d\'oeuvre classiques de l\'opéra français", Paris, c.1880s). Public domain, IMSLP #PMLP5360 (file IMSLP793400). Pages = printed pp. 46-50 (Cérémonie turque: Marche + 1re Entrée de ballet + Allah chorus + "Le Muphti parlé").',
    crop: 0.13,
    pages: local('lully', 5),
  },
  {
    composer: 'Anton Bruckner',
    title: 'Symphony No. 7 in E major — II. Adagio',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/0/07/HSO_Bruckner-7_02.mp3',
    performer: 'Hochschulsymphonieorchester München (University of Music and Theatre Munich), cond. Marcus Bosch — live 2020',
    license: 'recording CC BY-SA 4.0 · composition public domain',
    scoreNote: 'A.J. Gutmann engraved full score (first edition, Vienna 1885) — IMSLP #26842',
    crop: 0.085,
    pages: local('bruckner', 10),
  },
  {
    composer: 'Eugène Ysaÿe',
    title: 'Violin Sonata No. 3 in D minor, Op. 27 “Ballade”',
    audio: 'https://vmirror.imslp.org/files/imglnks/usimg/b/bd/IMSLP649627-PMLP12909-9_Sonata_III.mp3',
    performer: 'Ksenia Milas',
    license: 'Recording: CC BY-SA 4.0 (Ksenia Milas, ANIMA records, 2017). Score: public domain.',
    scoreNote: 'Éditions Ysaÿe (Aut. Ysaÿe, Éditeur), Brussels, 1924 — first edition, plate A.Y. 3332; IMSLP scan #876502 (catalogued on IMSLP as "Schott, Brussels 1924"). Public domain (pre-1930 engraving).',
    crop: 0.18,
    cropBottom: 0.09,
    pages: local('ysaye', 6),
  },
  {
    composer: 'Maurice Ravel',
    title: 'Jeux d\'eau',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c2/Ravel%27s_Jeux_d%27eau%2C_M._30_-_Anna_Sutyagina.ogg/Ravel%27s_Jeux_d%27eau%2C_M._30_-_Anna_Sutyagina.ogg.mp3',
    performer: 'Anna Sutyagina',
    license: 'Audio: CC BY 3.0 (Anna Sutyagina). Score: public domain (Demets 1902).',
    scoreNote: 'E. Demets, Paris, 1902, engraved edition, plate E. 12. D. Solo piano (original scoring). IMSLP #03175, file IMSLP03175-Ravel-Jeuxd\'Eau-Demets.pdf.',
    crop: 0.19,
    pages: local('jeuxdeau', 10),
  },
  {
    composer: 'Claude Debussy',
    title: 'Prélude à l’après-midi d’un faune',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/4/43/Columbia-dwx1550ix-c-wlx1289.ogg/Columbia-dwx1550ix-c-wlx1289.ogg.mp3',
    performer: 'Straram Symphony Orchestra (Orchestre Straram), cond. Walther Straram — Columbia 78rpm, rec. 24 Feb 1930, side 1 (matrix WLX 1289)',
    license: 'Public domain (Wikimedia Commons; 1930 recording, restoration by Public Domain Projekt / Carl Flisch)',
    scoreNote: 'Full orchestral score, A. Fromont (Paris), 1895 — engraved, plate no. E. 1091 F. (IMSLP)',
    crop: 0.26,
    pages: local('faune', 10),
  },
  {
    composer: 'Gustav Holst',
    title: 'The Planets — I. Mars, the Bringer of War',
    audio: 'https://archive.org/download/holst-the-planets-holst-london-symphony-orchestra-1922-1924/The%20Planets%20Op.%2032%2C%20H.%20125_%20I.%20Mars%2C%20The%20Bringer%20of%20War.mp3',
    performer: 'London Symphony Orchestra conducted by the composer himself (1922–24)',
    license: 'public domain',
    scoreNote: 'Goodwin & Tabb 1921 full score',
    crop: 0.11,
    pages: local('mars', 10),
  },
  {
    composer: 'Johann Sebastian Bach',
    title: 'Chaconne (Partita No. 2 in D minor, BWV 1004)',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/4/49/Johann_Sebastian_Bach_-_Chaconne_for_violin_alone.ogg/Johann_Sebastian_Bach_-_Chaconne_for_violin_alone.ogg.mp3',
    performer: 'Ben Goldstein (violin)',
    license: 'Audio: CC BY-SA 3.0 (Ben Goldstein; Al Goldstein collection / Pandora Music, EFF Open Audio License). Score: Public Domain.',
    scoreNote: 'Bach-Gesellschaft Ausgabe, Band 27 (ed. Alfred Dorffel), Breitkopf & Hartel, 1879 — original engraving; IMSLP #01307 (BWV1004.pdf)',
    crop: 0.1,
    cropBottom: 0.07,
    pages: local('chaconne', 6),
  },
  {
    composer: 'Franz Liszt',
    title: 'Totentanz',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/5/59/Liszt_Totentanz.ogg/Liszt_Totentanz.ogg.mp3',
    performer: 'Neal O\'Doan (piano) with orchestra',
    license: 'CC BY-SA 2.0',
    scoreNote: 'Breitkopf & Härtel full orchestral score (Franz Liszts Musikalische Werke, Serie I, Band 13), ed. Bernhard Stavenhagen, Leipzig 1915',
    crop: 0.24,
    pages: local('totentanz', 10),
  },
  {
    composer: 'Pyotr Ilyich Tchaikovsky',
    title: 'Romeo and Juliet — Overture-Fantasy',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a9/Pyotr_Ilyich_Tchaikovsky_-_romeo_and_juliet-_overture-fantasy.ogg/Pyotr_Ilyich_Tchaikovsky_-_romeo_and_juliet-_overture-fantasy.ogg.mp3',
    performer: 'Skidmore College Orchestra',
    license: 'public domain',
    scoreNote: 'Ed. Bote & G. Bock full orchestral score (Berlin, 1881) — original engraving of the 1880 final (3rd) version',
    crop: 0.13,
    pages: local('romeojuliet', 10),
  },
  {
    composer: 'Camille Saint-Saëns',
    title: 'Symphony No. 3 in C minor, Op. 78 “Organ” — Finale (Maestoso)',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/d/da/Symphony_No._3_in_C_Minor_-_II._Maestoso_-_Stellar_Brass_-_United_States_Air_Force_Academy_Band.mp3',
    performer: 'Stellar Brass, United States Air Force Academy Band',
    license: 'public domain (U.S. Air Force Academy Band)',
    scoreNote: 'Durand & Schoenewerk first edition full score, 1886 (Plate D.S. 3700)',
    crop: 0,
    pages: local('organsymphony', 10),
  },
  {
    composer: 'Richard Wagner',
    title: 'Die Meistersinger von Nürnberg — Overture',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a2/Richard_Wagner_-_die_meistersinger_von_nurnberg_-_overture.ogg/Richard_Wagner_-_die_meistersinger_von_nurnberg_-_overture.ogg.mp3',
    performer: 'Unidentified orchestra (Musopen public-domain recording)',
    license: 'public domain · Musopen',
    scoreNote: 'Ernst Eulenburg miniature full score, plate E.E. 3772 (Sibley Music Library scan)',
    crop: 0.12,
    pages: local('meistersinger', 10),
  },
  {
    composer: 'Robert Schumann',
    title: 'Piano Concerto in A minor, Op. 54 — I. Allegro affettuoso',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/e/ea/Schumann_-_Piano_Concerto_in_A_minor_Op.54_-_I._Allegro.ogg/Schumann_-_Piano_Concerto_in_A_minor_Op.54_-_I._Allegro.ogg.mp3',
    performer: 'Unknown orchestra & pianist (Musopen public-domain recording)',
    license: 'CC0 1.0 (Public Domain Dedication)',
    scoreNote: 'Breitkopf & Härtel complete-works full orchestral score (Robert Schumann\'s Werke, Serie III, No. 4, ed. Clara Schumann), Leipzig, issued 1883',
    crop: 0.17,
    pages: local('schumannconcerto', 10),
  },
  {
    composer: 'Jean Sibelius',
    title: 'The Swan of Tuonela',
    audio: 'https://archive.org/download/swan-of-tuonela-stokowski-1929/swan%20of%20tuonela%20%28stokowski%201929%29.mp3',
    performer: 'Leopold Stokowski, Philadelphia Orchestra; Marcel Tabuteau, cor anglais (Victor, rec. May 1929)',
    license: 'Public domain — historic 1929 Victor 78rpm recording (via Internet Archive); consistent with the repo\'s existing Victor-acoustic Finlandia entry',
    scoreNote: 'Breitkopf & Härtel, Leipzig, 1901 — full orchestral score, plate K.F.W.48 / Part.-B. 1654 (engraved). IMSLP #255071.',
    crop: 0.15,
    pages: local('swantuonela', 10),
  },
  {
    composer: 'Nikolai Rimsky-Korsakov',
    title: 'Capriccio Espagnol, Op. 34 — I. Alborada',
    audio: 'https://archive.org/download/MessagerConducts/01Rimsky-korsakov-CapriccioEspagnol.mp3',
    performer: 'Société des Concerts du Conservatoire de Paris, cond. André Messager (Columbia A6122, rec. New York, 19 Oct 1918; acoustic 78rpm; digital transfer by F. Reeder)',
    license: 'Public domain (US; recording published 1918, pre-1923); uploader\'s transfer released under CC BY-NC-SA 3.0',
    scoreNote: 'M. P. Belaieff full orchestral score (Partition d\'orchestre), Leipzig 1888 — engraved by C. G. Röder, plate 97 (IMSLP #32506)',
    crop: 0.11,
    pages: local('capriccioespagnol', 10),
  },
  {
    composer: 'Georges Bizet',
    title: 'L\'Arlésienne Suite No. 2 — IV. Farandole',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/a/ae/Victor_Herbert_Orchestra_-_08_-_1910_-_Farandole_from_LArlsienne_Bizet.ogg/Victor_Herbert_Orchestra_-_08_-_1910_-_Farandole_from_LArlsienne_Bizet.ogg.mp3',
    performer: 'Victor Herbert Orchestra (1910 Edison cylinder)',
    license: 'CC0 · public domain (1910 recording)',
    scoreNote: 'Choudens Père et Fils first-edition full orchestral score (Paris, n.d. [1879]; plate A.C. 4703)',
    crop: 0.1,
    pages: local('farandole', 10),
  },
  {
    composer: 'Gabriel Fauré',
    title: 'Sicilienne, Op. 78',
    audio: 'https://vmirror.imslp.org/files/imglnks/usimg/5/5d/IMSLP879702-PMLP20764-faure_siciliene.mp3',
    performer: 'Luis Kolodin (piano)',
    license: 'CC BY-SA 4.0 · IMSLP',
    scoreNote: 'J. Hamelle first edition, Paris 1898 (this copy a 1926 printing), engraved; original cello & piano scoring. IMSLP #21224, scanned by D-Mbs (Bayerische Staatsbibliothek). Public domain.',
    crop: 0.24,
    pages: local('sicilienne', 6),
  },
  {
    composer: 'Frédéric Chopin',
    title: 'Ballade No. 1 in G minor, Op. 23',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/6/61/Chopin_Ballade_no._1_in_G_minor%2C_Op._23_Frank_L%C3%A9vy.mp3',
    performer: 'Frank Lévy (piano)',
    license: 'CC BY 4.0',
    scoreNote: 'Schlesinger first edition, Paris 1836 (plate M.S. 1928)',
    crop: 0.14,
    pages: local('ballade1', 9),
  },
  {
    composer: 'Gioachino Rossini',
    title: 'La gazza ladra — Overture',
    audio: 'https://archive.org/download/edison-50124_01_2267/cusb_ed_50124_01_2267_0b.mp3',
    performer: 'Edison Concert Band (acoustic Diamond Disc, 1913)',
    license: 'public domain',
    scoreNote: 'Breitkopf & Härtel full orchestral score, ed. Gustav F. Kögel (Leipzig, c. 1900)',
    crop: 0.17,
    pages: local('gazzaladra', 10),
  },
  {
    composer: 'Edvard Grieg',
    title: 'Wedding Day at Troldhaugen, Op. 65 No. 6',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/6/6b/Grieg%2Bplays%2BGrieg%2BWedding%2BDay%2B%281903%29.ogg/Grieg%2Bplays%2BGrieg%2BWedding%2BDay%2B%281903%29.ogg.mp3',
    performer: 'Edvard Grieg (composer, 1903 recording)',
    license: 'Public domain',
    scoreNote: 'C. F. Peters, Leipzig 1897 engraved piano score (plate 8356, ed. Adolf Ruthardt)',
    crop: 0.24,
    cropBottom: 0.075,
    pages: local('troldhaugen', 10),
  },
  {
    composer: 'Felix Mendelssohn',
    title: 'Octet in E-flat major, Op. 20 — III. Scherzo',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/bd/The_Amadeus_Chamber_Orchestra_of_Polish_Radio_-_Mendelssohn%27s_String_Octet_in_E-flat_major%2C_Op._20%2C_MWV_R_20_-_III._Scherzo_allegro_leggierissimo.ogg/The_Amadeus_Chamber_Orchestra_of_Polish_Radio_-_Mendelssohn%27s_String_Octet_in_E-flat_major%2C_Op._20%2C_MWV_R_20_-_III._Scherzo_allegro_leggierissimo.ogg.mp3',
    performer: 'The Amadeus Chamber Orchestra of Polish Radio',
    license: 'CC BY 3.0',
    scoreNote: 'Full score, Breitkopf & Härtel (Mendelssohns Werke collected edition, ed. Julius Rietz), Leipzig, 1874–77; public domain engraving. IMSLP #07690, reformatted A4.',
    crop: 0.06,
    pages: local('octet', 10),
  },
  {
    composer: 'Antonín Dvořák',
    title: 'Serenade for Strings in E major, Op. 22 — I. Moderato',
    audio: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/d/d5/Dvorak_String_Serenade_I_Moderato.ogg/Dvorak_String_Serenade_I_Moderato.ogg.mp3',
    performer: 'Reinhold Behringer',
    license: 'CC BY-SA 4.0',
    scoreNote: 'Bote & Bock first-edition string-orchestra score, Berlin 1879',
    crop: 0.14,
    pages: local('dvorakserenade', 7),
  },
];

// Difficulty rebalance: these were authored in HARD but play as MEDIUM — too famous to be
// "niche". Kept as one editable list rather than relocating ten blocks; move a title in or
// out of this Set to retier it. (META still applies via the EASY/MEDIUM/HARD loop below.)
const HARD_TO_MEDIUM = new Set([
  'Caprice No. 24 in A minor',
  'Sì, mi chiamano Mimì (La bohème)',
  'Symphony No. 5 — IV. Adagietto',
  'Slavonic Dance in E minor, Op. 72 No. 2',
  'Danse macabre, Op. 40',
  'Prelude in C-sharp minor, Op. 3 No. 2',
  'Symphony No. 8 “Unfinished” — I. Allegro moderato',
  'The Four Seasons — “Winter”, RV 297, I.',
  'Anvil Chorus (Il trovatore)',
  'Pavane, Op. 50',
]);
const PIECES = {
  easy: EASY,
  medium: MEDIUM.concat(HARD.filter(p => HARD_TO_MEDIUM.has(p.title))),
  hard: HARD.filter(p => !HARD_TO_MEDIUM.has(p.title)),
};

// Per-piece guessing metadata: composition year (hint), genre (hint + feedback),
// genreWords (detect "right genre" in a wrong guess), keys (accepted piece-name answers,
// matched against a normalized guess with substring containment).
const META = {
  'Toccata and Fugue in D minor, BWV 565': { year: 1704, genre: 'organ work', genreWords: ['organ', 'toccata', 'fugue'], keys: ['toccata', 'bwv565'] },
  'Symphony No. 5 in C minor, Op. 67 — I. Allegro con brio': { year: 1808, genre: 'symphony', genreWords: ['symphony', 'symphonie'], keys: ['symphony5', 'fifthsymphony', 'fatesymphony'] },
  'Eine kleine Nachtmusik, K. 525 — I. Allegro': { year: 1787, genre: 'serenade', genreWords: ['serenade', 'nachtmusik'], keys: ['kleinenachtmusik', 'einekleine', 'nightmusic', 'k525'] },
  'The Four Seasons — “Spring”, RV 269, I. Allegro': { year: 1723, genre: 'violin concerto', genreWords: ['concerto', 'seasons'], keys: ['spring', 'fourseasons', 'primavera'] },
  'Symphony No. 94 “Surprise” — II. Andante': { year: 1791, genre: 'symphony', genreWords: ['symphony', 'symphonie'], keys: ['symphony94', 'surprise'] },
  'In the Hall of the Mountain King (Peer Gynt Suite No. 1)': { year: 1875, genre: 'orchestral suite', genreWords: ['suite', 'incidental'], keys: ['mountainking', 'peergynt'] },
  'Swan Lake, Op. 20 — Scène (the swan theme)': { year: 1876, genre: 'ballet', genreWords: ['ballet', 'lake'], keys: ['swanlake', 'lacdescygnes', 'swantheme'] },
  'Piano Sonata No. 2, Op. 35 — III. Marche funèbre': { year: 1839, genre: 'piano sonata', genreWords: ['sonata', 'march', 'marche'], keys: ['funeralmarch', 'marchefunebre', 'sonata2', 'pianosonata2'] },
  'Ride of the Valkyries (Die Walküre, Act III)': { year: 1856, genre: 'opera', genreWords: ['opera', 'valkyrie', 'walkure'], keys: ['valkyrie', 'walkure', 'ring'] },
  'Gymnopédie No. 1': { year: 1888, genre: 'piano piece', genreWords: ['piano'], keys: ['gymnopedie'] },
  'Hungarian Dance No. 5': { year: 1869, genre: 'dance', genreWords: ['dance', 'tanz'], keys: ['hungariandance'] },
  'Clair de lune (Suite bergamasque)': { year: 1905, genre: 'piano suite', genreWords: ['suite', 'piano'], keys: ['clairdelune', 'bergamasque'] },
  'Water Music — Alla Hornpipe': { year: 1717, genre: 'orchestral suite', genreWords: ['suite', 'hornpipe'], keys: ['watermusic', 'hornpipe'] },
  'Ave Maria (Ellens Gesang III, D. 839)': { year: 1825, genre: 'song', genreWords: ['song', 'lied', 'hymn'], keys: ['avemaria', 'ellensgesang'] },
  'Hungarian Rhapsody No. 2': { year: 1847, genre: 'rhapsody', genreWords: ['rhapsody', 'rhapsodie'], keys: ['hungarianrhapsody', 'rhapsody2'] },
  'La donna è mobile (Rigoletto)': { year: 1851, genre: 'opera', genreWords: ['opera', 'aria'], keys: ['ladonna', 'rigoletto'] },
  'Wedding March (A Midsummer Night’s Dream)': { year: 1842, genre: 'march', genreWords: ['march', 'marche'], keys: ['weddingmarch', 'midsummer'] },
  'The Swan (Carnival of the Animals)': { year: 1886, genre: 'suite movement', genreWords: ['suite', 'carnival'], keys: ['swan', 'cygne', 'carnival'] },
  'Träumerei (Kinderszenen, Op. 15 No. 7)': { year: 1838, genre: 'piano piece', genreWords: ['piano', 'scenes'], keys: ['traumerei', 'dreaming', 'reverie', 'kinderszenen'] },
  'Caprice No. 24 in A minor': { year: 1817, genre: 'violin caprice', genreWords: ['caprice', 'violin', 'etude'], keys: ['caprice24', 'caprice'] },
  'Sì, mi chiamano Mimì (La bohème)': { year: 1896, genre: 'opera', genreWords: ['opera', 'aria'], keys: ['mimi', 'boheme'] },
  'Symphony No. 5 — IV. Adagietto': { year: 1902, genre: 'symphony', genreWords: ['symphony', 'symphonie'], keys: ['adagietto', 'symphony5'] },
  'Holberg Suite — I. Praeludium': { year: 1884, genre: 'suite', genreWords: ['suite'], keys: ['holberg', 'praeludium'] },
  'Passacaglia and Fugue in C minor, BWV 582': { year: 1710, genre: 'organ work', genreWords: ['organ', 'fugue', 'passacaglia'], keys: ['passacaglia', 'bwv582'] },
  'Egmont Overture, Op. 84': { year: 1810, genre: 'overture', genreWords: ['overture', 'ouverture'], keys: ['egmont'] },
  'Slavonic Dance in E minor, Op. 72 No. 2': { year: 1886, genre: 'dance', genreWords: ['dance'], keys: ['slavonicdance', 'op72'] },
  'Danse macabre, Op. 40': { year: 1874, genre: 'tone poem', genreWords: ['tonepoem', 'symphonicpoem', 'danse'], keys: ['dansemacabre', 'macabre', 'danceofdeath'] },
  'Rondo alla turca (Piano Sonata K. 331)': { year: 1783, genre: 'piano sonata', genreWords: ['sonata', 'rondo', 'march'], keys: ['turkish', 'allaturca', 'turca', 'k331'] },
  'Nocturne in E-flat major, Op. 9 No. 2': { year: 1832, genre: 'nocturne', genreWords: ['nocturne'], keys: ['nocturne', 'op9'] },
  'Cello Suite No. 1 in G major — Prélude': { year: 1720, genre: 'cello suite', genreWords: ['suite', 'cello', 'prelude'], keys: ['cellosuite', 'suite1', 'bwv1007'] },
  'Liebestraum No. 3 in A-flat major': { year: 1850, genre: 'nocturne', genreWords: ['nocturne', 'dream'], keys: ['liebestraum', 'dreamoflove'] },
  'Piano Concerto No. 1 in B-flat minor — I.': { year: 1875, genre: 'piano concerto', genreWords: ['concerto'], keys: ['pianoconcerto1', 'concerto1'] },
  'Rhapsody in Blue': { year: 1924, genre: 'rhapsody', genreWords: ['rhapsody', 'jazz'], keys: ['rhapsodyinblue', 'blue'] },
  'Prelude in C-sharp minor, Op. 3 No. 2': { year: 1892, genre: 'prelude', genreWords: ['prelude'], keys: ['preludeinc', 'op3', 'bells'] },
  'Symphony No. 8 “Unfinished” — I. Allegro moderato': { year: 1822, genre: 'symphony', genreWords: ['symphony', 'symphonie'], keys: ['unfinished', 'symphony8', 'unvollendete'] },
  'Piano Sonata No. 14 “Moonlight” — I. Adagio sostenuto': { year: 1801, genre: 'piano sonata', genreWords: ['sonata'], keys: ['moonlight', 'mondschein', 'sonata14', 'op27'] },
  'Symphony No. 9 “From the New World” — II. Largo': { year: 1893, genre: 'symphony', genreWords: ['symphony', 'symphonie'], keys: ['newworld', 'symphony9', 'goinhome', 'largo'] },
  'Messiah — Hallelujah chorus': { year: 1741, genre: 'oratorio', genreWords: ['oratorio', 'chorus', 'choral'], keys: ['hallelujah', 'messiah'] },
  'Symphony No. 40 in G minor — I. Molto allegro': { year: 1788, genre: 'symphony', genreWords: ['symphony', 'symphonie'], keys: ['symphony40', 'k550', 'gminor'] },
  'Symphony No. 9 — Finale (Ode to Joy)': { year: 1824, genre: 'symphony', genreWords: ['symphony', 'symphonie', 'choral'], keys: ['symphony9', 'ninth', 'odetojoy', 'choralsymphony', 'freude'] },
  'The Nutcracker — March': { year: 1892, genre: 'ballet', genreWords: ['ballet', 'suite'], keys: ['nutcracker', 'cassenoisette'] },
  'Morning Mood (Peer Gynt Suite No. 1)': { year: 1875, genre: 'orchestral suite', genreWords: ['suite', 'incidental'], keys: ['morningmood', 'morning', 'peergynt', 'morgenstimmung'] },
  'The Marriage of Figaro — Overture': { year: 1786, genre: 'opera overture', genreWords: ['overture', 'ouverture', 'opera'], keys: ['figaro', 'nozze'] },
  'Marche militaire No. 1': { year: 1818, genre: 'march', genreWords: ['march', 'marche'], keys: ['marchemilitaire', 'militarymarch', 'militaire'] },
  'Air on the G String (Orchestral Suite No. 3)': { year: 1730, genre: 'orchestral suite', genreWords: ['suite'], keys: ['airongstring', 'gstring', 'bwv1068', 'suite3'] },
  'The Planets — IV. Jupiter': { year: 1916, genre: 'orchestral suite', genreWords: ['suite', 'planets'], keys: ['jupiter', 'planets'] },
  '1812 Overture': { year: 1880, genre: 'overture', genreWords: ['overture', 'ouverture'], keys: ['1812'] },
  'The Four Seasons — “Winter”, RV 297, I.': { year: 1723, genre: 'violin concerto', genreWords: ['concerto', 'seasons'], keys: ['winter', 'inverno', 'fourseasons'] },
  'Anvil Chorus (Il trovatore)': { year: 1853, genre: 'opera', genreWords: ['opera', 'chorus', 'choral'], keys: ['anvil', 'trovatore'] },
  'William Tell Overture': { year: 1829, genre: 'overture', genreWords: ['overture', 'ouverture'], keys: ['williamtell', 'tell', 'guillaumetell'] },
  'The Blue Danube': { year: 1867, genre: 'waltz', genreWords: ['waltz', 'walzer', 'danube', 'donau'], keys: ['bluedanube', 'danube', 'donau'] },
  'Dance of the Sugar Plum Fairy': { year: 1892, genre: 'ballet', genreWords: ['ballet', 'nutcracker', 'suite'], keys: ['sugarplumfairy', 'sugarplum', 'nutcracker'] },
  'Pomp and Circumstance March No. 1': { year: 1901, genre: 'march', genreWords: ['march', 'marche'], keys: ['pompandcircumstance', 'pomp'] },
  'The Moldau': { year: 1874, genre: 'tone poem', genreWords: ['tonepoem', 'symphonicpoem', 'moldau', 'vltava'], keys: ['moldau', 'vltava'] },
  'Arabesque No. 1': { year: 1888, genre: 'piano piece', genreWords: ['arabesque', 'piano'], keys: ['arabesque', 'arabesque1'] },
  'Carmen — Prelude': { year: 1875, genre: 'overture', genreWords: ['overture', 'prelude', 'opera'], keys: ['carmen', 'carmenprelude', 'carmenoverture'] },
  'Flight of the Bumblebee': { year: 1900, genre: 'orchestral interlude', genreWords: ['interlude', 'orchestral', 'bumblebee', 'bee'], keys: ['flightofthebumblebee', 'bumblebee', 'flightofbumblebee', 'bumble'] },
  'Canon in D': { year: 1680, genre: 'canon', genreWords: ['canon'], keys: ['canonind', 'canon', 'pachelbelscanon'] },
  'Orpheus in the Underworld — Can-Can (Galop infernal)': { year: 1858, genre: 'can-can', genreWords: ['cancan', 'galop', 'operetta', 'opera'], keys: ['cancan', 'galopinfernal', 'infernalgalop', 'orpheus', 'orpheusintheunderworld', 'orpheeauxenfers'] },
  'Finlandia': { year: 1899, genre: 'tone poem', genreWords: ['tonepoem', 'tone', 'poem', 'symphonic', 'finlandia'], keys: ['finlandia'] },
  'Night on Bald Mountain': { year: 1867, genre: 'tone poem', genreWords: ['tonepoem', 'symphonicpoem', 'tone', 'poem', 'symphonic', 'fantasy'], keys: ['nightonbaldmountain', 'baldmountain', 'nightonbaremountain', 'baremountain'] },
  'Brandenburg Concerto No. 3 — I. Allegro': { year: 1721, genre: 'concerto', genreWords: ['concerto', 'brandenburg'], keys: ['brandenburgconcerto3', 'brandenburg3', 'bwv1048'] },
  'Symphony No. 7 — II. Allegretto': { year: 1812, genre: 'symphony', genreWords: ['symphony', 'allegretto'], keys: ['symphony7', 'beethoven7', 'seventhsymphony', 'allegretto'] },
  'Fantaisie-Impromptu, Op. 66': { year: 1834, genre: 'piano piece', genreWords: ['impromptu', 'fantaisie', 'fantasy', 'fantasie'], keys: ['fantaisieimpromptu', 'fantasieimpromptu', 'fantasyimpromptu', 'impromptu'] },
  'Lacrimosa (Requiem, K. 626)': { year: 1791, genre: 'requiem', genreWords: ['requiem', 'mass', 'lacrimosa'], keys: ['lacrimosa', 'requiem'] },
  'Symphonie fantastique — IV. March to the Scaffold': { year: 1830, genre: 'march', genreWords: ['march', 'marche', 'scaffold', 'supplice', 'fantastique'], keys: ['symphoniefantastique', 'fantastique', 'marchtothescaffold', 'marcheausupplice', 'scaffold'] },
  'Pavane, Op. 50': { year: 1887, genre: 'pavane', genreWords: ['pavane', 'dance'], keys: ['pavane', 'pavaneop50'] },
  'Pavane pour une infante défunte': { year: 1899, genre: 'pavane', genreWords: ['pavane'], keys: ['pavanepour', 'infantedefunte', 'deadprincess', 'm19'] },
  'The Firebird — Infernal Dance': { year: 1910, genre: 'ballet', genreWords: ['ballet', 'dance'], keys: ['firebird', 'thefirebird', 'firebirdsuite', 'infernaldance', 'danseinfernale', 'loiseaudefeu', 'oiseaudefeu', 'k10'] },
  'March from The Love for Three Oranges, Op. 33': { year: 1919, genre: 'march', genreWords: ['march', 'marche', 'marcia'], keys: ['loveforthreeoranges', 'threeoranges', 'lamourdestroisoranges', 'op33'] },
  'Enigma Variations — IX. Nimrod': { year: 1899, genre: 'variation', genreWords: ['variation', 'variations'], keys: ['nimrod', 'enigma', 'op36'] },
  'Valse triste, Op. 44': { year: 1904, genre: 'waltz', genreWords: ['waltz', 'valse', 'walzer'], keys: ['valsetriste', 'sadwaltz', 'op44'] },
  'Mephisto Waltz No. 1': { year: 1861, genre: 'waltz', genreWords: ['waltz', 'walzer', 'valse'], keys: ['mephistowaltz', 'mephisto', 's514', 'dertanzinderdorfschenke'] },
  'The Hebrides (Fingal’s Cave) Overture, Op. 26': { year: 1830, genre: 'concert overture', genreWords: ['overture', 'ouverture'], keys: ['hebrides', 'thehebrides', 'fingalscave', 'diehebriden', 'fingalshohle', 'op26'] },
  'Scheherazade, Op. 35 — I. The Sea and Sinbad’s Ship': { year: 1888, genre: 'symphonic suite', genreWords: ['symphonicsuite', 'suite', 'symphonicpoem', 'tonepoem'], keys: ['scheherazade', 'sheherazade', 'op35', 'theseaandsinbadsship', 'seaandsinbadsship'] },
  'Tannhäuser — Overture': { year: 1845, genre: 'overture', genreWords: ['overture', 'ouverture'], keys: ['tannhauser', 'tannhauseroverture', 'overturetotannhauser', 'wwv70'] },
  'Carnival Overture, Op. 92': { year: 1891, genre: 'concert overture', genreWords: ['overture', 'ouverture'], keys: ['carnival', 'carneval', 'op92', 'b169'] },
  'Symphony No. 3 in F major, Op. 90 — III. Poco allegretto': { year: 1883, genre: 'symphony', genreWords: ['symphony', 'symphonie'], keys: ['symphony3', 'brahms3', 'thirdsymphony', 'op90', 'pocoallegretto'] },
  'Bacchanale (Samson et Dalila)': { year: 1877, genre: 'ballet music', genreWords: ['bacchanale', 'ballet', 'dance', 'opera'], keys: ['bacchanale', 'dansebacchanale', 'samsonetdalila', 'samsondalila', 'op47'] },
  'The Barber of Seville — Overture': { year: 1816, genre: 'overture', genreWords: ['overture', 'ouverture', 'opera'], keys: ['barberofseville', 'thebarberofseville', 'barber', 'ilbarbieredisiviglia', 'barbieredisiviglia'] },
  'Barcarolle (The Tales of Hoffmann)': { year: 1881, genre: 'barcarolle', genreWords: ['barcarolle', 'barcarole', 'opera'], keys: ['barcarolle', 'barcarole', 'bellenuit', 'talesofhoffmann', 'lescontesdhoffmann', 'contesdhoffmann', 'hoffmann'] },
  'Sarabande in D minor, HWV 437': { year: 1733, genre: 'sarabande', genreWords: ['sarabande', 'suite', 'dance'], keys: ['sarabande', 'sarabandeindminor', 'sarabandehwv437', 'hwv437'] },
  'Piano Concerto in A minor, Op. 16 — I. Allegro molto moderato': { year: 1868, genre: 'concerto', genreWords: ['concerto'], keys: ['pianoconcertoinaminor', 'pianoconcerto', 'concertoinaminor', 'op16', 'opus16'] },
  'The Four Seasons — “Summer”, RV 315, III. Presto': { year: 1723, genre: 'violin concerto', genreWords: ['concerto', 'seasons'], keys: ['summer', 'estate', 'fourseasons', 'rv315'] },
  'Keyboard Sonata in E major, K. 380': { year: 1754, genre: 'Keyboard sonata', genreWords: ['sonata', 'keyboard', 'harpsichord'], keys: ['k380', 'sonatak380', 'sonatainemajork380', 'keyboardsonatainemajork380', 'l23', 'longo23', 'p483', 'kirkpatrick380', 'cortege'] },
  'Marche pour la cérémonie des Turcs': { year: 1670, genre: 'Baroque march (from a comédie-ballet)', genreWords: ['march', 'marche', 'baroque', 'ballet', 'suite'], keys: ['ceremoniedesturcs', 'marchedesturcs', 'marcheturque', 'turcs', 'lwv43'] },
  'Violin Concerto No. 1 in G minor, Op. 26 — I. Vorspiel': { year: 1866, genre: 'violin concerto', genreWords: ['concerto', 'violin'], keys: ['violinconcerto1', 'violinconcerto1ingminor', 'concertoingminor', 'op26', 'opus26'] },
  'Symphony No. 7 in E major — II. Adagio': { year: 1883, genre: 'symphony', genreWords: ['symphony', 'symphonie', 'adagio'], keys: ['symphony7', 'bruckner7', 'seventhsymphony', 'wab107', 'adagio'] },
  'Violin Sonata No. 3 in D minor, Op. 27 “Ballade”': { year: 1923, genre: 'sonata for solo violin', genreWords: ['sonata', 'violin'], keys: ['ballade', 'sonata3', 'op273'] },
  'Jeux d\'eau': { year: 1901, genre: 'Solo piano (Impressionist)', genreWords: ['piano', 'solo', 'impressionist', 'impressionism'], keys: ['jeuxdeau', 'm30'] },
  'Prélude à l’après-midi d’un faune': { year: 1894, genre: 'Symphonic poem (orchestral)', genreWords: ['symphonic', 'poem', 'tone', 'prelude', 'orchestral', 'impressionist'], keys: ['preludealapresmididunfaune', 'lapresmididunfaune', 'preludetotheafternoonofafaun', 'preludetoafternoonofafaun', 'afternoonofafaun', 'l86'] },
  'The Planets — I. Mars, the Bringer of War': { year: 1916, genre: 'orchestral suite', genreWords: ['suite', 'planets'], keys: ['mars', 'planets', 'marsthebringerofwar', 'thebringerofwar'] },
  'Chaconne (Partita No. 2 in D minor, BWV 1004)': { year: 1720, genre: 'Baroque solo violin chaconne (variations)', genreWords: ['chaconne', 'ciaccona', 'partita', 'sonata', 'violin', 'solo', 'suite', 'baroque'], keys: ['chaconne', 'ciaccona', 'bwv1004'] },
  'Totentanz': { year: 1849, genre: 'variations for piano and orchestra', genreWords: ['variations', 'variation', 'paraphrase', 'concertante'], keys: ['totentanz', 's126', 'diesirae'] },
  'Romeo and Juliet — Overture-Fantasy': { year: 1880, genre: 'overture-fantasy', genreWords: ['overture', 'ouverture', 'fantasy', 'fantasia', 'fantaisie'], keys: ['romeoandjuliet', 'romeojuliet', 'th42'] },
  'Symphony No. 3 in C minor, Op. 78 “Organ” — Finale (Maestoso)': { year: 1886, genre: 'symphony', genreWords: ['symphony', 'symphonie'], keys: ['symphony3', 'organsymphony', 'organ', 'thirdsymphony', 'op78'] },
  'Die Meistersinger von Nürnberg — Overture': { year: 1868, genre: 'Opera overture (orchestral prelude)', genreWords: ['overture', 'prelude', 'vorspiel', 'opera'], keys: ['meistersinger', 'wwv96'] },
  'Piano Concerto in A minor, Op. 54 — I. Allegro affettuoso': { year: 1845, genre: 'piano concerto', genreWords: ['concerto'], keys: ['pianoconcertoinaminor', 'pianoconcerto', 'concertoinaminor', 'op54', 'opus54'] },
  'The Swan of Tuonela': { year: 1895, genre: 'tone poem', genreWords: ['tonepoem', 'symphonicpoem', 'tone', 'poem', 'symphonic', 'legend'], keys: ['tuonela', 'swanoftuonela', 'op22'] },
  'Capriccio Espagnol, Op. 34 — I. Alborada': { year: 1887, genre: 'orchestral capriccio', genreWords: ['capriccio', 'caprice', 'suite', 'rhapsody', 'orchestral'], keys: ['capriccioespagnol', 'capriccioespagnole', 'capricciospagnolo', 'spanishcaprice', 'spanishcapriccio', 'op34', 'alborada'] },
  'L\'Arlésienne Suite No. 2 — IV. Farandole': { year: 1872, genre: 'orchestral suite', genreWords: ['suite', 'incidental'], keys: ['farandole', 'arlesienne'] },
  'Sicilienne, Op. 78': { year: 1893, genre: 'sicilienne', genreWords: ['sicilienne', 'siciliano'], keys: ['sicilienne', 'op78'] },
  'Ballade No. 1 in G minor, Op. 23': { year: 1835, genre: 'piano ballade', genreWords: ['ballade', 'ballad'], keys: ['ballade1', 'firstballade'] },
  'La gazza ladra — Overture': { year: 1817, genre: 'overture', genreWords: ['overture', 'ouverture', 'opera'], keys: ['lagazzaladra', 'gazzaladra', 'thievingmagpie', 'thethievingmagpie', 'diediebischeelster'] },
  'Wedding Day at Troldhaugen, Op. 65 No. 6': { year: 1896, genre: 'piano piece', genreWords: ['piano', 'lyric'], keys: ['troldhaugen', 'weddingday', 'op65'] },
  'Octet in E-flat major, Op. 20 — III. Scherzo': { year: 1825, genre: 'String octet (chamber music)', genreWords: ['octet', 'string', 'scherzo', 'chamber'], keys: ['octet', 'stringoctet', 'octetineflatmajor', 'op20', 'mwvr20'] },
  'Clarinet Concerto in A major, K. 622 — II. Adagio': { year: 1791, genre: 'clarinet concerto', genreWords: ['concerto', 'clarinet'], keys: ['clarinetconcerto', 'clarinetconcertoinamajor', 'k622', 'kv622'] },
  'The Four Seasons — “Autumn”, RV 293, I. Allegro': { year: 1723, genre: 'violin concerto', genreWords: ['concerto', 'seasons'], keys: ['autumn', 'autunno', 'fourseasons', 'rv293'] },
  'Arrival of the Queen of Sheba (Solomon)': { year: 1748, genre: 'Baroque oratorio sinfonia (orchestral interlude)', genreWords: ['baroque', 'oratorio', 'sinfonia', 'overture', 'orchestral'], keys: ['arrivalofthequeenofsheba', 'queenofsheba', 'hwv67'] },
  'Vocalise, Op. 34 No. 14': { year: 1915, genre: 'song', genreWords: ['song', 'romance', 'lied'], keys: ['vocalise', 'op34'] },
  'Serenade for Strings in E major, Op. 22 — I. Moderato': { year: 1875, genre: 'serenade', genreWords: ['serenade', 'strings', 'string', 'orchestra'], keys: ['serenadeforstrings', 'serenadeinemajor', 'stringserenade', 'op22', 'b52'] },
};
for (const pool of [EASY, MEDIUM, HARD]) for (const p of pool) Object.assign(p, META[p.title]);

// Daily pick: first prime stride that doesn't divide the pool → full cycle before repeats.
function pieceIndex(date, pool) {
  const dn = (typeof dayNumber !== 'undefined' ? dayNumber : require('./_game.js').dayNumber)(date);
  const n = pool.length;
  const stride = [7, 5, 3, 2].find(s => n % s !== 0) || 1;
  return ((dn * stride + 3) % n + n) % n;
}

if (typeof module !== 'undefined') module.exports = { PIECES, pieceIndex };
